-- *******************************************************
-- Script de creación de tabla PERSON
-- *******************************************************

DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    NATIONAL_ID VARCHAR(100) UNIQUE,
    NATIONAL_HEALTH_ID VARCHAR(100) UNIQUE,

    PERSON_TYPE ENUM('DOCTOR', 'NURSE',  'PATIENT', 'EMPLOYEE', 'ADMIN', 'SUPER_ADMIN') NOT NULL,

    NOMBRE VARCHAR(50) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(50),
    APELLIDO_PATERNO VARCHAR(50) NOT NULL,
    APELLIDO_MATERNO VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    ESTADO_CIVIL ENUM('SOLTERO','CASADO', 'UNION_LIBRE', 'SEPARADO', 'DIVORCIADO','VIUDO') DEFAULT NULL,
    GENERO ENUM('MASCULINO','FEMENINO','OTRO') DEFAULT NULL,

    FK_ID_ADDRESS BIGINT DEFAULT NULL,
    TELEFONO VARCHAR(50),
    CELULAR VARCHAR(50),

    -- ===============================
    -- Auditoría
    -- ===============================
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT FK_PERSON_ADDRESS FOREIGN KEY (FK_ID_ADDRESS) REFERENCES ADDRESS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
