-- *******************************************************
-- Script de creación de tabla PERSON_TENANT
-- *******************************************************

DROP TABLE IF EXISTS PERSON_TENANT;

CREATE TABLE PERSON_TENANT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_PERSON BIGINT NOT NULL,
    FK_ID_TENANT BIGINT NOT NULL,
    NATIONAL_HEALTH_ID VARCHAR(50),
    ROLE_CONTEXT ENUM  ('SUPER_ADMIN', 'TENANT_ADMIN', 'DOCTOR', 'PATIENT', 'NURSE', 'EMPLOYEE', 'RECEPTIONIST', 'LAB_TECHNICIAN') NOT NULL,

    DATE_REGISTERED TIMESTAMP NOT NULL,
    DATE_UNREGISTERED TIMESTAMP,
    RELATION_STATUS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', 'TERMINATED', 'EXPIRED', 'ARCHIVED', 'LOCKED', 'DEACTIVATED') NOT NULL,

    -- ===============================
    -- Auditoría
    -- ===============================
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
