-- *******************************************************
-- Script de creación de tabla SUPER_ADMIN
-- *******************************************************
CREATE TABLE IF NOT EXISTS SUPER_ADMIN (
    ID BIGINT PRIMARY KEY NOT NULL,
    LEVEL ENUM('LEVEL_1','LEVEL_2','LEVEL_3') NOT NULL,
    GLOBAL_ACCESS BOOLEAN NOT NULL DEFAULT FALSE,
    USER_ID BIGINT NOT NULL,

    CONSTRAINT FK_SUPER_ADMIN_PERSON FOREIGN KEY (ID) REFERENCES PERSON(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SUPER_ADMIN_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
