-- *******************************************************
-- Script de creación de tabla TENANT_ADMIN
-- *******************************************************

DROP TABLE IF EXISTS TENANT_ADMIN;

CREATE TABLE TENANT_ADMIN (
    ID BIGINT PRIMARY KEY NOT NULL,
    ADMIN_LEVEL ENUM('LEVEL_1','LEVEL_2','LEVEL_3') NOT NULL,
    TENANT_CODE VARCHAR(100) NOT NULL,

    CONSTRAINT FK_TENANT_ADMIN_PERSON FOREIGN KEY (ID) REFERENCES PERSON(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TENANT_ADMIN_TENANT FOREIGN KEY (TENANT_CODE) REFERENCES TENANT(CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
