-- *******************************************************
-- Script de creación de tabla TENANT_CONFIG
-- *******************************************************

DROP TABLE IF EXISTS TENANT_CONFIG;

CREATE TABLE TENANT_CONFIG (
    ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TENANT_ID BIGINT NOT NULL UNIQUE,
    FALLBACK_HEADER VARCHAR(100),
    ALLOW_LOCAL TINYINT(1),
    DEFAULT_DOMAIN VARCHAR(200),
    LOCALE VARCHAR(20),
    TIMEZONE VARCHAR(100),
    MAX_USERS INT,
    STORAGE_QUOTA_BYTES BIGINT,
    REQUIRE_EMAIL_VERIFICATION TINYINT(1),
    PASSWORD_POLICY_JSON TEXT,
    EXTRA_JSON TEXT,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    CONSTRAINT FK_TENANT_CONFIG_TENANT
        FOREIGN KEY (TENANT_ID) REFERENCES TENANT(ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

