DROP TABLE IF EXISTS PERSON;

CREATE TABLE IF NOT EXISTS `PERSON` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	`PERSON_TYPE` ENUM('SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'NURSE', 'PATIENT', 'USER') NOT NULL DEFAULT 'USER',
	`NOMBRE` VARCHAR(50) NOT NULL,
	`SEGUNDO_NOMBRE` VARCHAR(50) NULL DEFAULT NULL,
	`APELLIDO_PATERNO` VARCHAR(50) NOT NULL,
	`APELLIDO_MATERNO` VARCHAR(50),
	`FECHA_NACIMIENTO` DATE NULL DEFAULT NULL,
	`ESTADO_CIVIL` ENUM('SOLTERO', 'CASADO', 'UNION_LIBRE', 'SEPARADO', 'DIVORCIADO', 'VIUDO'),
	`GENERO` ENUM('MASCULINO', 'FEMENINO', 'DESCONOCIDO'),
	`FK_ID_ADDRESS` BIGINT NULL DEFAULT NULL,
    `TELEFONO` VARCHAR(50) NULL DEFAULT NULL,
    `CELULAR` VARCHAR(50) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(255) NULL DEFAULT NULL,
    `CREATED_DATE` DATETIME NULL DEFAULT NULL,
    `LAST_MODIFIED_BY` VARCHAR(255) NULL DEFAULT NULL,
    `LAST_MODIFIED_DATE` DATETIME NULL DEFAULT NULL,
	CONSTRAINT FK_PERSON_ADDRESS FOREIGN KEY (FK_ID_ADDRESS) REFERENCES ADDRESS(ID)
);
commit;