DROP TABLE IF EXISTS ROLE;

CREATE TABLE IF NOT EXISTS ROLE (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `CREATED_BY` VARCHAR(100) NOT NULL,
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED_BY` VARCHAR(100),
    `LAST_MODIFIED_DATE` TIMESTAMP
);
commit;
