DROP TABLE IF EXISTS ROLE;

CREATE TABLE IF NOT EXISTS ROLE (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
--    ROLE_NAME ENUM('USER', 'ADMIN', 'MODERATOR', 'GUEST', 'SUPER_ADMIN', 'CONTENT_CREATOR', 'CONTENT_EDITOR', 'SUPPORT', 'ANALYST') NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `CREATED_BY` VARCHAR(100) NOT NULL,
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED_BY` VARCHAR(100),
    `LAST_MODIFIED_DATE` TIMESTAMP
);
commit;
