DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS USER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ACCOUNT_LOCKED BOOLEAN NOT NULL DEFAULT TRUE,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    FK_ID_PERSON BIGINT UNIQUE,
    AVATAR LONGBLOB,
--    `PERSON_TYPE` ENUM('ADMIN', 'DOCTOR', 'NURSE', 'PATIENT', 'USER') NOT NULL DEFAULT 'USER',
    `CREATED_BY` VARCHAR(100) NOT NULL,
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED_BY` VARCHAR(100),
    `LAST_MODIFIED_DATE` TIMESTAMP,
    CONSTRAINT FK_USER_PERSON FOREIGN KEY (FK_ID_PERSON) REFERENCES PERSON(ID) ON DELETE CASCADE
);
commit;
