
CREATE TABLE COUNTRY (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ISO VARCHAR(2) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    NICE_NAME VARCHAR(100) NOT NULL,
    ISO3 VARCHAR(3),
    NUM_CODE INT DEFAULT NULL,
    PHONE_CODE INT NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL,
    UNIQUE KEY UK_NAME_COUNTRY (NAME),
    UNIQUE KEY UK_ISO_COUNTRY (ISO)
);
