DROP TABLE IF EXISTS DEPARTAMENTO_HOSPITAL;

CREATE TABLE DEPARTAMENTO_HOSPITAL (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) DEFAULT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL,
    UNIQUE KEY UK_NAME_DEPARTAMENTO_HOSPITAL (NAME)
);
commit;

