-- ==============================================
-- V29__create_user_profile_and_related.sql
-- Crea la tabla USER_PROFILE y sus entidades hijas:
-- EDUCATION, EXPERIENCE, COURSE, CONFERENCE
-- Incluye inserts de prueba.
-- ==============================================

-- 1. Tabla USER_PROFILE
CREATE TABLE IF NOT EXISTS USER_PROFILE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BIOGRAPHY VARCHAR(2000),
    PHOTO MEDIUMBLOB
);

-- 2. Tabla EDUCATION
CREATE TABLE IF NOT EXISTS EDUCATION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    INSTITUTION VARCHAR(100) NOT NULL,
    DEGREE VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    FK_ID_USERPROFILE BIGINT NOT NULL,
    CONSTRAINT FK_EDUCATION_USERPROFILE FOREIGN KEY (FK_ID_USERPROFILE)
        REFERENCES USER_PROFILE(ID) ON DELETE CASCADE
);

-- 3. Tabla EXPERIENCE
CREATE TABLE IF NOT EXISTS EXPERIENCE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    INSTITUTION VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    DESCRIPTION VARCHAR(500),
    FK_ID_USERPROFILE BIGINT NOT NULL,
    CONSTRAINT FK_EXPERIENCE_USERPROFILE FOREIGN KEY (FK_ID_USERPROFILE)
        REFERENCES USER_PROFILE(ID) ON DELETE CASCADE
);

-- 4. Tabla COURSE
CREATE TABLE IF NOT EXISTS COURSE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    INSTITUTION VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    DATE DATE NOT NULL,
    DURATION_IN_HOURS INT NOT NULL,
    CERTIFICATE VARCHAR(255),
    FK_ID_USERPROFILE BIGINT NOT NULL,
    CONSTRAINT FK_COURSE_USERPROFILE FOREIGN KEY (FK_ID_USERPROFILE)
        REFERENCES USER_PROFILE(ID) ON DELETE CASCADE
);

-- 5. Tabla CONFERENCE
CREATE TABLE IF NOT EXISTS CONFERENCE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TOPIC VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    ORGANIZER VARCHAR(100),
    LOCATION VARCHAR(255),
    IS_INTERNATIONAL BOOLEAN NOT NULL,
    DATE DATE NOT NULL,
    FK_ID_USERPROFILE BIGINT NOT NULL,
    CONSTRAINT FK_CONFERENCE_USERPROFILE FOREIGN KEY (FK_ID_USERPROFILE)
        REFERENCES USER_PROFILE(ID) ON DELETE CASCADE
);