DROP TABLE IF EXISTS TOKEN;

CREATE TABLE IF NOT EXISTS TOKEN (
    `ID` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `TOKEN` VARCHAR(500) NOT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `EXPIRED_AT` DATETIME NOT NULL,
    `VALIDATED_AT` DATETIME NULL,
    `FK_ID_USER` BIGINT NOT NULL,
    CONSTRAINT FK_TOKEN_USER FOREIGN KEY (FK_ID_USER) REFERENCES USER(ID)
);
commit;
