DROP TABLE IF EXISTS ADMIN;

CREATE TABLE IF NOT EXISTS ADMIN (
    `ID` BIGINT PRIMARY KEY NOT NULL,
    `PHOTO` MEDIUMBLOB,
    FOREIGN KEY (ID) REFERENCES PERSON(ID) ON DELETE CASCADE -- Herencia JOINED
);
commit;
