DROP TABLE IF EXISTS NURSE_PROFESSION_SPECIALITY;

-- DROP TABLE IF EXISTS NURSE_PROFESSION_SPECIALITY;
CREATE TABLE IF NOT EXISTS NURSE_PROFESSION_SPECIALITY (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(250) NULL,
	CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL,
	UNIQUE INDEX `UK_NAME_NURSE_PROFESSION_SPECIALITY` (`NAME`)
);
commit;

