CREATE TABLE IF NOT EXISTS DOCTOR (
    ID BIGINT PRIMARY KEY, -- misma PK que PERSON
    LICENSE_NUMBER VARCHAR(100) UNIQUE,
    IS_AVAILABLE BOOLEAN DEFAULT TRUE,
    SPECIALTIES_SUMMARY VARCHAR(255),
    YEARS_OF_EXPERIENCE INT,
    RATING DECIMAL(3,1),
    FK_ID_USERPROFILE BIGINT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DOCTOR_PERSON FOREIGN KEY (ID) REFERENCES PERSON(ID),
    CONSTRAINT FK_DOCTOR_USERPROFILE FOREIGN KEY (FK_ID_USERPROFILE) REFERENCES USER_PROFILE(ID)
);

COMMIT;
