-- Tabla DEPARTAMENTO_TIPO (DepartamentoTipo)
CREATE TABLE DEPARTAMENTO_TIPO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(500) NULL,
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP
);

-- Tabla DEPARTAMENTO_HOSPITAL
CREATE TABLE DEPARTAMENTO_HOSPITAL (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_HOSPITAL BIGINT NOT NULL,
    FK_ID_DEPARTAMENTO_TIPO BIGINT NOT NULL,
    FK_ID_HEAD_DOCTOR BIGINT,

    DESCRIPTION VARCHAR(500),
    FLOOR VARCHAR(20),
    CONTACT_PHONE VARCHAR(20),

    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP,

    CONSTRAINT FK_DEPARTAMENTOHOSPITAL_HOSPITAL FOREIGN KEY (FK_ID_HOSPITAL)
        REFERENCES HOSPITAL(ID),

    CONSTRAINT FK_DEPARTAMENTOHOSPITAL_DEPARTAMENTO_TIPO FOREIGN KEY (FK_ID_DEPARTAMENTO_TIPO)
        REFERENCES DEPARTAMENTO_TIPO(ID),

    CONSTRAINT FK_DEPARTAMENTOHOSPITAL_HEADDOCTOR FOREIGN KEY (FK_ID_HEAD_DOCTOR)
        REFERENCES DOCTOR(ID)
);
commit;

