DROP TABLE IF EXISTS NURSE;

-- DROP TABLE IF EXISTS NURSE;
CREATE TABLE IF NOT EXISTS NURSE (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `PHOTO` MEDIUMBLOB,
    `ID_CARD` VARCHAR(100) UNIQUE
);
commit;

