DROP TABLE IF EXISTS NURSE;

-- DROP TABLE IF EXISTS NURSE;
CREATE TABLE IF NOT EXISTS NURSE (
    `ID` BIGINT PRIMARY KEY NOT NULL,
    `PHOTO` MEDIUMBLOB,
    `ID_CARD` VARCHAR(100) UNIQUE,
    CONSTRAINT FK_NURSE_PERSON FOREIGN KEY (ID) REFERENCES PERSON(ID) ON DELETE CASCADE -- Herencia JOINED
);
commit;

