DROP TABLE IF EXISTS NURSE_NURSEPROFESSIONSPECIALITY;

CREATE TABLE IF NOT EXISTS `NURSE_NURSEPROFESSIONSPECIALITY` (
  `ID_NURSE` BIGINT NOT NULL,
  `ID_NURSE_PROFESSION_SPECIALITY` BIGINT NOT NULL,
  PRIMARY KEY (`ID_NURSE`,`ID_NURSE_PROFESSION_SPECIALITY`),
  CONSTRAINT `FK_ID_NURSE` FOREIGN KEY (`ID_NURSE`) REFERENCES `NURSE` (`ID`),
  CONSTRAINT `FK_ID_NURSE_PROFESSION_SPECIALITY` FOREIGN KEY (`ID_NURSE_PROFESSION_SPECIALITY`) REFERENCES `NURSE_PROFESSION_SPECIALITY` (`ID`)
);
commit;

