CREATE TABLE IF NOT EXISTS DOCTOR_PROFESSION_SPECIALITY (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(250),
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255) NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS DOCTOR_DOCTORPROFESSIONSPECIALITY (
    ID_DOCTOR BIGINT NOT NULL,
    ID_DOCTOR_PROFESSION_SPECIALITY BIGINT NOT NULL,
    PRIMARY KEY (ID_DOCTOR, ID_DOCTOR_PROFESSION_SPECIALITY),
    CONSTRAINT FK_DDPS_DOCTOR FOREIGN KEY (ID_DOCTOR)
        REFERENCES DOCTOR(ID),
    CONSTRAINT FK_DDPS_SPECIALITY FOREIGN KEY (ID_DOCTOR_PROFESSION_SPECIALITY)
        REFERENCES DOCTOR_PROFESSION_SPECIALITY(ID)
);
commit;

