-- Tabla principal NURSE
CREATE TABLE IF NOT EXISTS NURSE (
    ID BIGINT PRIMARY KEY, -- Hereda el ID de PERSON
    PHOTO MEDIUMBLOB,
    ID_CARD VARCHAR(100) UNIQUE,
    FK_ID_USERPROFILE BIGINT NOT NULL,
    CREATED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NURSE_PERSON FOREIGN KEY (ID) REFERENCES PERSON(ID),
    CONSTRAINT FK_NURSE_USERPROFILE FOREIGN KEY (FK_ID_USERPROFILE) REFERENCES USER_PROFILE(ID)
);

commit;

