CREATE TABLE IF NOT EXISTS DOCTOR_HOSPITAL_ASSIGNMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,

    FK_ID_DOCTOR BIGINT NOT NULL,
    FK_ID_HOSPITAL BIGINT NOT NULL,

    START_DATE DATE NOT NULL,
    END_DATE DATE,

    CONSTRAINT FK_DOCTORHOSPITALASSIGNMENT_DOCTOR FOREIGN KEY (FK_ID_DOCTOR)
        REFERENCES DOCTOR(ID),

    CONSTRAINT FK_DOCTORHOSPITALASSIGNMENT_HOSPITAL FOREIGN KEY (FK_ID_HOSPITAL)
        REFERENCES HOSPITAL(ID)
);
COMMIT;
