CREATE TABLE IF NOT EXISTS TIPO_CONSULTA (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(150) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(250),
    ESPECIALIDAD VARCHAR(150)
);
COMMIT;
