CREATE TABLE IF NOT EXISTS ROOM (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NUMBER_ROOM INT,
    CAPACITY INT,
    PRIVATE_ROOM BOOLEAN DEFAULT FALSE,
    TYPE_ROOM ENUM(
        'ESTANDAR',
        'SUITE',
        'CUIDADOS_INTENSIVOS',
        'PEDIATRICOS',
        'PARTOS',
        'AISLAMIENTO',
        'OBSERVACION',
        'ONCOLOGIA',
        'DIALISIS',
        'CUIDADOS_PALIATIVOS'
    ) DEFAULT 'ESTANDAR',
    NUMBER_OF_BEDS INT,
    BLOCK_FLOOR INT,
    BLOCK_CODE VARCHAR(10) NOT NULL,
    UNAVAILABLE BOOLEAN,
    FK_ID_HOSPITAL BIGINT NOT NULL,
    CONSTRAINT FK_ROOM_HOSPITAL FOREIGN KEY (FK_ID_HOSPITAL) REFERENCES HOSPITAL(ID)
);
COMMIT;