CREATE TABLE IF NOT EXISTS INSURANCE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    INSURANCE_NUMBER INT,
    NAME VARCHAR(255) NOT NULL,
    TELEPHONE VARCHAR(50),
    FAX VARCHAR(50),
    WEB_SITE VARCHAR(100),
    INSURANCE_DATE DATE,
    EXPIRATION_DATE DATE,
    FK_ID_ADDRESS BIGINT,
    CONTACT_PERSON VARCHAR(255),
    CONTACT_EMAIL VARCHAR(255),
    POLICY_TYPE VARCHAR(255),
    POLICY_DETAILS TEXT,
    CONSTRAINT FK_INSURANCE_ADDRESS FOREIGN KEY (FK_ID_ADDRESS) REFERENCES ADDRESS(ID)
);
COMMIT;