CREATE TABLE IF NOT EXISTS HABITO_TOXICO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ALCOHOL VARCHAR(200),
    TABACO VARCHAR(200),
    DROGAS VARCHAR(200),
    INFUSIONES VARCHAR(200),
    CAFEINA VARCHAR(200),
    COMIDA_CHATARRA VARCHAR(200),
    SEDENTARISMO VARCHAR(200),
    OTROS VARCHAR(200)
);
COMMIT;