CREATE TABLE IF NOT EXISTS HABITO_FISIOLOGICO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUTRICION VARCHAR(250),
    URINACION VARCHAR(250),
    DEFECACION VARCHAR(250),
    SUENO VARCHAR(250),
    SEXUALIDAD VARCHAR(250),
    ALERGIAS VARCHAR(250),
    ACTIVIDADES_DEPORTIVAS VARCHAR(250),
    OTROS VARCHAR(250)
);
COMMIT;