CREATE TABLE IF NOT EXISTS HISTORIA_FAMILIAR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INFORMACION_SALUD_MADRE VARCHAR(200),
    INFORMACION_SALUD_PADRE VARCHAR(200),
    INFORMACION_SALUD_HERMANOS VARCHAR(200),
    INFORMACION_SALUD_ABUELOS VARCHAR(200),
    HISTORIAL_ENFERMEDADES_CARDIACAS_FAMILIARES VARCHAR(200),
    HISTORIAL_ENFERMEDADES_MENTALES_FAMILIARES VARCHAR(200),
    INFORMACION_SALUD_HIJOS VARCHAR(200),
    INFORMACION_SALUD_OTROS_PARIENTES VARCHAR(200),
    HISTORIAL_DIABETES_FAMILIAR VARCHAR(200),
    HISTORIAL_CANCER_FAMILIAR VARCHAR(200),
    ETNIA_FAMILIA VARCHAR(100),
    NOTAS_ADICIONALES VARCHAR(500),
    FECHA_REGISTRO_HISTORIA_FAMILIAR DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION_HISTORIA_FAMILIAR DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ENFERMEDADES_HEREDITARIAS (
    ID_HISTORIA_FAMILIAR BIGINT NOT NULL,
    ENFERMEDAD VARCHAR(255) NOT NULL,
    CONSTRAINT FK_ENFERMEDADES_HISTORIA_FAMILIAR FOREIGN KEY (ID_HISTORIA_FAMILIAR) REFERENCES HISTORIA_FAMILIAR(ID)
);

COMMIT;