DROP TABLE IF EXISTS `PROVINCIA`;
CREATE TABLE IF NOT EXISTS `PROVINCIA` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `NOMBRE` VARCHAR(100) NOT NULL,
    `POBLACION` INT DEFAULT NULL,
    `SUPERFICIE` DECIMAL DEFAULT NULL,
    `FK_ID_DEPARTAMENTO` BIGINT,
    `CREATED_BY` VARCHAR(100) NOT NULL,
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED_BY` VARCHAR(100) NOT NULL,
    `LAST_MODIFIED_DATE` TIMESTAMP NOT NULL,
    CONSTRAINT `FK_PROVINCIA_DEPARTAMENTO` FOREIGN KEY (`FK_ID_DEPARTAMENTO`) REFERENCES `DEPARTAMENTO` (`ID`),
    UNIQUE KEY `UK_NOMBRE_PROVINCIA` (`NOMBRE`)
);
COMMIT;