INSERT INTO HISTORIA_FAMILIAR (
    INFORMACION_SALUD_MADRE, INFORMACION_SALUD_PADRE, INFORMACION_SALUD_HERMANOS,
    INFORMACION_SALUD_ABUELOS, HISTORIAL_ENFERMEDADES_CARDIACAS_FAMILIARES,
    HISTORIAL_ENFERMEDADES_MENTALES_FAMILIARES, FECHA_REGISTRO_HISTORIA_FAMILIAR,
    FECHA_ACTUALIZACION_HISTORIA_FAMILIAR, INFORMACION_SALUD_HIJOS,
    INFORMACION_SALUD_OTROS_PARIENTES, HISTORIAL_DIABETES_FAMILIAR,
    HISTORIAL_CANCER_FAMILIAR, ETNIA_FAMILIA, NOTAS_ADICIONALES
) VALUES (
    'Sin problemas', 'Diabetes tipo 2', 'Hipertensión', 'Ninguno',
    'Cardiopatía isquémica', 'Depresión', NOW(), NOW(),
    'Ninguno', 'Ninguno', 'Diabetes tipo 2',
    'Ninguno', 'Mestizo', 'Sin observaciones'
);

-- Supongamos que el ID generado de HistoriaFamiliar fue 1
INSERT INTO ENFERMEDADES_HEREDITARIAS (ID_HISTORIA_FAMILIAR, ENFERMEDAD) VALUES
(1, 'Diabetes'),
(1, 'Hipertensión'),
(1, 'Cardiopatía');

COMMIT;