CREATE TABLE IF NOT EXISTS HISTORIA_MEDICA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,

    FK_ID_PATIENT BIGINT NOT NULL,
    FK_ID_DOCTOR BIGINT NOT NULL,
    FK_ID_HOSPITAL BIGINT NOT NULL,
    DATE DATE NOT NULL,
    ADMISSION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    OBSERVATIONS VARCHAR(1000),
    CONSTRAINT FK_HISTORIAMEDICA_PATIENT FOREIGN KEY (FK_ID_PATIENT) REFERENCES PATIENT(ID),
    CONSTRAINT FK_HISTORIAMEDICA_DOCTOR FOREIGN KEY (FK_ID_DOCTOR) REFERENCES DOCTOR(ID),
    CONSTRAINT FK_HISTORIAMEDICA_HOSPITAL FOREIGN KEY (FK_ID_HOSPITAL) REFERENCES HOSPITAL(ID)
);
COMMIT;
