INSERT INTO HISTORIA_MEDICA (FK_ID_PATIENT, FK_ID_DOCTOR, FK_ID_HOSPITAL, DATE, ADMISSION_DATE, OBSERVATIONS)
VALUES
(1, 2, 1, '2023-01-10', CURRENT_TIMESTAMP, 'Paciente con historial sin complicaciones');
commit;