CREATE TABLE PATIENT_VISIT (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_PATIENT BIGINT NOT NULL,
    FK_ID_HOSPITAL BIGINT NOT NULL,
    VISIT_DATE DATE,
    FK_ID_HISTORIAMEDICA BIGINT,
    VISIT_TYPE ENUM(
        'CONSULTA_EXTERNA',
        'VISITA_EMERGENCIA',
        'INGRESO_HOSPITALARIO',
        'VISITA_QUIRURGICA',
        'VISITA_DIAGNOSTICA',
        'VISITA_SEGUIMIENTO',
        'TRASLADO_ENTRADA',
        'TELECONSULTA',
        'VISITA_ADMINISTRATIVA',
        'OTRO'
    ) NOT NULL,

    CONSTRAINT FK_PATIENTVISIT_PATIENT FOREIGN KEY (FK_ID_PATIENT) REFERENCES PATIENT(id),
    CONSTRAINT FK_PATIENTVISIT_HOSPITAL FOREIGN KEY (FK_ID_HOSPITAL) REFERENCES HOSPITAL(id),
    CONSTRAINT FK_PATIENTVISIT_HISTORIAMEDICA FOREIGN KEY (FK_ID_HISTORIAMEDICA) REFERENCES HISTORIA_MEDICA(id)
);
COMMIT;