INSERT INTO PATIENT_VISIT (
    FK_ID_PATIENT,
    FK_ID_HOSPITAL,
    VISIT_DATE,
    FK_ID_HISTORIAMEDICA,
    VISIT_TYPE
) VALUES (
    1,
    2,
    '2025-07-21',
    1,
    'CONSULTA_EXTERNA'
);
COMMIT;