CREATE TABLE HOSPITALIZACION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    FECHA_INGRESO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_EGRESO TIMESTAMP NULL,

    MOTIVO_INGRESO VARCHAR(255),
    MOTIVO_EGRESO VARCHAR(255),
    DIAGNOSTICO VARCHAR(255),
    TRATAMIENTO VARCHAR(255),
    OBSERVACIONES VARCHAR(255),

    FK_ID_ROOM BIGINT,
    FK_ID_PATIENT_VISIT BIGINT NOT NULL,
    FK_ID_DEPARTAMENTO_HOSPITAL BIGINT,

    PROCEDIMIENTOS_REALIZADOS TEXT,
    INSTRUCCIONES_PLAN_ALTA TEXT,
    CONDICION_AL_ALTA VARCHAR(200),
    COMPLICACIONES_DURANTE_ESTANCIA TEXT,
    RESUMEN_EXAMEN_FISICO_INGRESO TEXT,
    TIPO_ADMISION VARCHAR(100),

    CONSTRAINT FK_HOSPITALIZACION_ROOM FOREIGN KEY (FK_ID_ROOM) REFERENCES ROOM(ID),
    CONSTRAINT FK_HOSPITALIZACION_PATIENTVISIT FOREIGN KEY (FK_ID_PATIENT_VISIT) REFERENCES PATIENT_VISIT(ID),
    CONSTRAINT FK_HOSPITALIZACION_DEPARTAMENTOHOSPITAL FOREIGN KEY (FK_ID_DEPARTAMENTO_HOSPITAL) REFERENCES DEPARTAMENTO_HOSPITAL(ID)
);

CREATE TABLE MEDICAMENTOS_AL_ALTA (
    ID_HOSPITALIZACION BIGINT NOT NULL,
    MEDICAMENTO VARCHAR(255),

    CONSTRAINT FK_MEDICAMENTOS_HOSPITALIZACION FOREIGN KEY (ID_HOSPITALIZACION)
        REFERENCES HOSPITALIZACION(ID)
);

COMMIT;