CREATE TABLE IF NOT EXISTS REGISTRO_ENFERMEDAD (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE_ENFERMEDAD VARCHAR(255),
    DESCRIPCION TEXT,
    SINTOMAS TEXT,
    TRATAMIENTOS TEXT,
    FK_ID_HISTORIA_MEDICA BIGINT,
    CONSTRAINT FK_RE_HM FOREIGN KEY (FK_ID_HISTORIA_MEDICA) REFERENCES HISTORIA_MEDICA(ID)
);
COMMIT;