CREATE TABLE IF NOT EXISTS ENFERMEDAD_ACTUAL (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(255),
    FECHA_DIAGNOSTICO DATE,
    SINTOMAS TEXT,
    TRATAMIENTOS TEXT,
    FK_ID_HISTORIA_MEDICA BIGINT,
    CONSTRAINT FK_EA_HM FOREIGN KEY (FK_ID_HISTORIA_MEDICA) REFERENCES HISTORIA_MEDICA(ID)
);
COMMIT;
