CREATE TABLE IF NOT EXISTS CONSULTA_MEDICA (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ESTADO_CONSULTA ENUM('PROGRAMADA', 'EN_ESPERA', 'EN_CURSO', 'COMPLETADA', 'CANCELADA', 'REPROGRAMADA', 'NO_ASISTIO'),
    FK_ID_TIPO_CONSULTA BIGINT NOT NULL,
    FECHA_CONSULTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FK_ID_DOCTOR BIGINT NOT NULL,
    MOTIVO_CONSULTA TEXT,
    SINTOMAS TEXT,
    DIAGNOSTICO TEXT,
    TRATAMIENTO TEXT,
    RECOMENDACIONES TEXT,
    FECHA_PROXIMA_CITA TIMESTAMP,
    OBSERVACIONES TEXT,
    FK_ID_HISTORIA_MEDICA BIGINT NOT NULL,
    CONSTRAINT FK_CM_TIPO FOREIGN KEY (FK_ID_TIPO_CONSULTA) REFERENCES TIPO_CONSULTA(ID),
    CONSTRAINT FK_CM_DOCTOR FOREIGN KEY (FK_ID_DOCTOR) REFERENCES DOCTOR(ID),
    CONSTRAINT FK_CM_HM FOREIGN KEY (FK_ID_HISTORIA_MEDICA) REFERENCES HISTORIA_MEDICA(ID)
);
COMMIT;
