INSERT INTO CONSULTA_MEDICA (
    ESTADO_CONSULTA, FK_ID_TIPO_CONSULTA, FECHA_CONSULTA, FK_ID_DOCTOR, MOTIVO_CONSULTA,
    SINTOMAS, DIAGNOSTICO, TRATAMIENTO, RECOMENDACIONES, FK_ID_HISTORIA_MEDICA
)
VALUES
('PROGRAMADA', 1, CURRENT_TIMESTAMP, 2 , 'Chequeo general',
 'Sin síntomas', 'Salud normal', 'Ninguno', 'Continuar con hábitos saludables', 1);
commit;