
-- Tabla Municipio
-- DROP TABLE IF EXISTS `MUNICIPIO`;
CREATE TABLE IF NOT EXISTS `MUNICIPIO` (
    `ID` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `NOMBRE` VARCHAR(100) NOT NULL,
    `POBLACION` INT DEFAULT NULL,
    `SUPERFICIE` DECIMAL(38,2) DEFAULT NULL,
    `DIRECCION` VARCHAR(200) DEFAULT NULL,
    `CODIGO_MUNICIPIO` INT DEFAULT NULL,
    `FK_ID_PROVINCIA` BIGINT DEFAULT NULL,
    `CREATED_BY` VARCHAR(100) NOT NULL,
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED_BY` VARCHAR(100) NOT NULL,
    `LAST_MODIFIED_DATE` TIMESTAMP NOT NULL,
    CONSTRAINT `FK_MUNICIPIO_PROVINCIA` FOREIGN KEY (`FK_ID_PROVINCIA`) REFERENCES `PROVINCIA` (`ID`),
    UNIQUE KEY `UK_NOMBRE_MUNICIPIO` (`NOMBRE`)
);
COMMIT;