/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IdentificationType } from '../../models/identification-type';

export interface UpdateIdentificationType$Params {

/**
 * ID del Identification Type a actualizar.
 */
  id: number;
      body: IdentificationType
}

export function updateIdentificationType(http: HttpClient, rootUrl: string, params: UpdateIdentificationType$Params, context?: HttpContext): Observable<StrictHttpResponse<IdentificationType>> {
  const rb = new RequestBuilder(rootUrl, updateIdentificationType.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IdentificationType>;
    })
  );
}

updateIdentificationType.PATH = '/mdm/identification-type/{id}';
