-- ============================================
-- Script: V1__create_tenant.sql
-- Tabla: TENANT
-- ============================================
DROP TABLE IF EXISTS TENANT;

CREATE TABLE TENANT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CODE VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    TYPE ENUM('HOSPITAL','CLINICA','LABORATORIO','PHARMACY') NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    DESCRIPTION VARCHAR(255) NULL,

    -- ===============================
    -- Auditoría
    -- ===============================
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_TENANT_CODE  UNIQUE (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Índices adicionales
-- ============================================
CREATE INDEX IDX_TENANT_NAME ON TENANT(NAME);

COMMIT;


--DROP TABLE IF EXISTS USER_ROLES;
--CREATE TABLE IF NOT EXISTS USER_ROLES (
--    USER_ID BIGINT NOT NULL,
--    ROLE_ID BIGINT NOT NULL,
--    PRIMARY KEY (USER_ID, ROLE_ID),
--    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE,
--    CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE
--
--);
--commit;