DROP TABLE IF EXISTS REFRESH_TOKEN;

CREATE TABLE REFRESH_TOKEN (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TOKEN VARCHAR(255) NOT NULL,
    USER_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,
    EXPIRY_DATE TIMESTAMP(6) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    REVOKED BIT(1) NOT NULL DEFAULT 0,

    CONSTRAINT UK_REFRESH_TOKEN_TOKEN UNIQUE (TOKEN),

    CONSTRAINT FK_REFRESH_TOKEN_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USER (ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_REFRESH_TOKEN_TENANT
        FOREIGN KEY (TENANT_ID)
        REFERENCES TENANT (ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
