
CREATE TABLE IF NOT EXISTS USER_TENANT_ROLE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_USER BIGINT NOT NULL,
    FK_ID_TENANT BIGINT NOT NULL,
    FK_ID_ROLE BIGINT NOT NULL,
    ASSIGNED_AT DATETIME NOT NULL,
    REVOKED_AT DATETIME NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_USER_TENANT_ROLE UNIQUE (FK_ID_USER, FK_ID_TENANT, FK_ID_ROLE),

    -- Foreign Keys
    CONSTRAINT FK_USERTENANTROLE_USER
        FOREIGN KEY (FK_ID_USER) REFERENCES USER (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_USERTENANTROLE_TENANT
        FOREIGN KEY (FK_ID_TENANT) REFERENCES TENANT (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_USERTENANTROLE_ROLE
        FOREIGN KEY (FK_ID_ROLE) REFERENCES ROLE (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Índices para mejorar el rendimiento de las consultas
CREATE INDEX IDX_USERTENANTROLE_USER ON USER_TENANT_ROLE (FK_ID_USER);
CREATE INDEX IDX_USERTENANTROLE_TENANT ON USER_TENANT_ROLE (FK_ID_TENANT);
CREATE INDEX IDX_USERTENANTROLE_ROLE ON USER_TENANT_ROLE (FK_ID_ROLE);
CREATE INDEX IDX_USERTENANTROLE_ACTIVE ON USER_TENANT_ROLE (ACTIVE);
CREATE INDEX IDX_USERTENANTROLE_ASSIGNED_AT ON USER_TENANT_ROLE (ASSIGNED_AT);
CREATE INDEX IDX_USERTENANTROLE_REVOKED_AT ON USER_TENANT_ROLE (REVOKED_AT);