-- ==========================================================
-- Table: USER
-- ==========================================================
CREATE TABLE IF NOT EXISTS USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ACCOUNT_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_LOGIN TIMESTAMP NULL DEFAULT NULL,
    PERSON_ID BIGINT,

    -- ===============================
    -- Auditoría
    -- ===============================
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
