DROP TABLE IF EXISTS USER_ACCOUNT ;

CREATE TABLE IF NOT EXISTS USER_ACCOUNT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    PERSON_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,
     -- ===============================
    -- Auditoría
    -- ===============================
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT FK_USER_ACCOUNTUSER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    CONSTRAINT FK_USER_ACCOUNTTENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANT(ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;