DROP TABLE IF EXISTS USER_ACCOUNT_ROLE ;

CREATE TABLE USER_ACCOUNT_ROLE (
    USER_ACCOUNT_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,

    CONSTRAINT PK_USER_ACCOUNT_ROLE PRIMARY KEY (USER_ACCOUNT_ID, ROLE_ID),
    CONSTRAINT FK_USER_ACCOUNT_ROLE_USERACCOUNT FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID),
    CONSTRAINT FK_USER_ACCOUNT_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;