DROP TABLE IF EXISTS ACTIVATION_TOKEN;

CREATE TABLE ACTIVATION_TOKEN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    TOKEN VARCHAR(100) NOT NULL UNIQUE,

    USER_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,

    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED BOOLEAN NOT NULL DEFAULT FALSE,

    -- ===============================
    -- Auditoría si quieres agregar
    -- ===============================
    CREATED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT FK_ACTIVATION_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    CONSTRAINT FK_ACTIVATION_TOKEN_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANT(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Índices opcionales
CREATE INDEX IDX_ACTIVATION_TOKEN_USER ON ACTIVATION_TOKEN(USER_ID);
CREATE INDEX IDX_ACTIVATION_TOKEN_TENANT ON ACTIVATION_TOKEN(TENANT_ID);
CREATE INDEX IDX_ACTIVATION_TOKEN_TOKEN ON ACTIVATION_TOKEN(TOKEN);