/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThemeDto } from '../../models/theme-dto';

export interface CreateTheme$Params {
      body: ThemeDto
}

export function createTheme(http: HttpClient, rootUrl: string, params: CreateTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
  const rb = new RequestBuilder(rootUrl, createTheme.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThemeDto>;
    })
  );
}

createTheme.PATH = '/themes';
