/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CivilStatusSearchDto } from '../../models/civil-status-search-dto';
import { PageResponseDtoCivilStatus } from '../../models/page-response-dto-civil-status';

export interface GetPaginatedCivilStatuses$Params {
  searchDto: CivilStatusSearchDto;

/**
 * Índice de la página a recuperar.
 */
  pageIndex: number;

/**
 * Tamaño de la página.
 */
  pageSize: number;
}

export function getPaginatedCivilStatuses(http: HttpClient, rootUrl: string, params: GetPaginatedCivilStatuses$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoCivilStatus>> {
  const rb = new RequestBuilder(rootUrl, getPaginatedCivilStatuses.PATH, 'get');
  if (params) {
    rb.query('searchDto', params.searchDto, {});
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoCivilStatus>;
    })
  );
}

getPaginatedCivilStatuses.PATH = '/mdm/demographic/civil-status';
