/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CivilStatus } from '../../models/civil-status';

export interface GetAllCivilStatuses$Params {
}

export function getAllCivilStatuses(http: HttpClient, rootUrl: string, params?: GetAllCivilStatuses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CivilStatus>>> {
  const rb = new RequestBuilder(rootUrl, getAllCivilStatuses.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CivilStatus>>;
    })
  );
}

getAllCivilStatuses.PATH = '/mdm/demographic/civil-status/all';
