spring:
  security:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: bolivia
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        discriminator:
          ignore_explicit_for_joined: true
        dialect: org.hibernate.dialect.MySQL8Dialect    # MySQL 8
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect    # MySQL 8
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    username: maildev
    password: maildev
    properties:
      mail:
        smtp:
          trust: "*"
        auth: false
        starttls:
          enable: false
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

mailing:
  frontend:
    activation-url: http://localhost:4200/#/activate-account

# Configuración de avatares
app:
  avatar:
    max-size: 1048576 # 1MB
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif
    default-path: classpath:templates/avatars/default-avatar.jpg
    storage: Error al almacenar el avatar {0}
    processing: Error al procesar el avatar {0}
    default:
      load: No se pudo cargar la imagen de perfil por defecto

## OpenAPI configuration
openapi:
  title: OpenAPI specification - ${spring.application.name}
  version: 1.0
  description: This API exposes endpoints to manage ${spring.application.name}
  terms-of-service: https://www.amachi.com/terms
  license:
    name: MIT License
    url: https://www.amachi.com/license
  contact:
    name: Juan Amachi
    email: juan.amachi@gmail.com
    url: https://www.amachi.com

hospital:
  default:
    code: "HOSPITAL_CLINICA_MULHOUSE"

#  flyway:
#    url: jdbc:mysql://localhost:3306/hospital_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#    user: root
#    password: bolivia
#    enabled: true
#    baseline-on-migrate: true
#    baseline-description: Baseline for hospital database
#    baseline-version: 1.0.0