/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Gender } from '../../models/gender';

export interface CreateGender$Params {
      body: Gender
}

export function createGender(http: HttpClient, rootUrl: string, params: CreateGender$Params, context?: HttpContext): Observable<StrictHttpResponse<Gender>> {
  const rb = new RequestBuilder(rootUrl, createGender.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Gender>;
    })
  );
}

createGender.PATH = '/mdm/demographic/gender';
