/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Gender } from '../../models/gender';

export interface GetGenderById$Params {

/**
 * ID del Gender a recuperar
 */
  id: number;
}

export function getGenderById(http: HttpClient, rootUrl: string, params: GetGenderById$Params, context?: HttpContext): Observable<StrictHttpResponse<Gender>> {
  const rb = new RequestBuilder(rootUrl, getGenderById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Gender>;
    })
  );
}

getGenderById.PATH = '/mdm/demographic/gender/{id}';
