-- *******************************************************
-- Script de creación de tabla DMN_PERSON
-- *******************************************************

CREATE TABLE IF NOT EXISTS DMN_PERSON (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,

    NATIONAL_ID VARCHAR(100) UNIQUE,
    NATIONAL_HEALTH_ID VARCHAR(100) UNIQUE,
    PERSON_TYPE VARCHAR(50) NOT NULL,

    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    SECOND_LAST_NAME VARCHAR(50),
    BIRTH_DATE DATE,
    MARITAL_STATUS VARCHAR(30) DEFAULT NULL,
    GENDER VARCHAR(30) DEFAULT NULL,
    IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,

    FK_ID_ADDRESS BIGINT DEFAULT NULL,
    PHONE_NUMBER VARCHAR(50),
    MOBILE_NUMBER VARCHAR(50),
    EMAIL VARCHAR(100),
    DOCUMENT_TYPE ENUM('DNI', 'PASSPORT', 'FOREIGN_ID', 'HEALTH_CARD', 'DRIVER_LICENSE', 'SOCIAL_SECURITY', 'OTHER') DEFAULT 'DNI',

    -- Auditoría Profesional
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME(6) NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),

    -- Constraints
    CONSTRAINT FK_PERSON_ADDRESS FOREIGN KEY (FK_ID_ADDRESS) REFERENCES GEO_ADDRESS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
