-- ============================================
-- Script: V3_7__create_dmn_hospital.sql
-- Tabla: DMN_HOSPITAL (JOINED Inheritance)
-- ============================================

CREATE TABLE IF NOT EXISTS DMN_HOSPITAL (
    TENANT_ID BIGINT PRIMARY KEY,
    LEGAL_NAME VARCHAR(200) NOT NULL,
    TAX_ID VARCHAR(50) NOT NULL,
    MEDICAL_LICENSE VARCHAR(100) NOT NULL,
    WEBSITE VARCHAR(255),
    CONTACT_PHONE VARCHAR(50),
    CONTACT_EMAIL VARCHAR(100),
    
    -- Fase 13: Campos Profesionales
    MEDICAL_DIRECTOR VARCHAR(150),
    MEDICAL_DIRECTOR_LICENSE VARCHAR(100),
    HOSPITAL_CATEGORY VARCHAR(100),
    BED_CAPACITY INT,
    OPERATING_ROOMS_COUNT INT,
    EMERGENCY_247 BIT(1),
    SLOGAN VARCHAR(255),
    FAX_NUMBER VARCHAR(50),
    WHATSAPP_NUMBER VARCHAR(50),
    SOCIAL_LINKS TEXT,
    SEAL_URL VARCHAR(255),

    -- Auditoría Profesional (JOINED inheritance consistency)
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME(6) NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),

    CONSTRAINT FK_HOSPITAL_TENANT FOREIGN KEY (TENANT_ID) REFERENCES DMN_TENANT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_HOSPITAL_TAX_ID ON DMN_HOSPITAL(TAX_ID);
CREATE INDEX IDX_HOSPITAL_LEGAL_NAME ON DMN_HOSPITAL(LEGAL_NAME);
