-- *******************************************************
-- Script de creación de tabla MGT_SUPER_ADMIN
-- *******************************************************
CREATE TABLE IF NOT EXISTS MGT_SUPER_ADMIN (
    ID BIGINT PRIMARY KEY NOT NULL,
    TENANT_ID VARCHAR(50) NOT NULL,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0 NOT NULL,
    LEVEL ENUM('LEVEL_1','LEVEL_2','LEVEL_3') NOT NULL,
    GLOBAL_ACCESS BOOLEAN NOT NULL DEFAULT FALSE,
    USER_ID BIGINT NOT NULL,

    CONSTRAINT FK_SUPER_ADMIN_PERSON FOREIGN KEY (ID) REFERENCES DMN_PERSON(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SUPER_ADMIN_USER FOREIGN KEY (USER_ID) REFERENCES AUT_USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
