-- *******************************************************
-- Script de creación de tabla MGT_TENANT_CONFIG
-- *******************************************************

CREATE TABLE IF NOT EXISTS MGT_TENANT_CONFIG (
    ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TENANT_ID BIGINT NOT NULL UNIQUE,
    FALLBACK_HEADER VARCHAR(100),
    ALLOW_LOCAL BIT(1),
    DEFAULT_DOMAIN VARCHAR(200),
    LOCALE VARCHAR(20),
    TIMEZONE VARCHAR(100),
    MAX_USERS INT,
    STORAGE_QUOTA_BYTES BIGINT,
    REQUIRE_EMAIL_VERIFICATION BIT(1),
    PASSWORD_POLICY_JSON TEXT,
    EXTRA_JSON TEXT,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,
    CONSTRAINT FK_TENANTCONFIG_TENANT
        FOREIGN KEY (TENANT_ID) REFERENCES DMN_TENANT(ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

