-- *******************************************************
-- Script de creación de tabla MGT_TENANT_CONFIG
-- *******************************************************

CREATE TABLE IF NOT EXISTS MGT_TENANT_CONFIG (
    ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TENANT_ID VARCHAR(50) NOT NULL UNIQUE,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0 NOT NULL,
    FALLBACK_HEADER VARCHAR(100),
    ALLOW_LOCAL BIT(1),
    DEFAULT_DOMAIN VARCHAR(200),
    LOCALE VARCHAR(20),
    TIMEZONE VARCHAR(100),
    MAX_USERS INT,
    STORAGE_QUOTA_BYTES BIGINT,
    REQUIRE_EMAIL_VERIFICATION BIT(1),
    SUBSCRIPTION_PLAN VARCHAR(50),
    ONBOARDING_DATE DATE,
    EXPIRATION_DATE DATE,
    PASSWORD_POLICY_JSON TEXT,
    EXTRA_JSON TEXT,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME(6) NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

