-- ============================================
-- Script: V8_6__expand_tenant_config.sql
-- Expansión de MGT_TENANT_CONFIG (Suscripciones)
-- ============================================

ALTER TABLE MGT_TENANT_CONFIG ADD COLUMN SUBSCRIPTION_PLAN VARCHAR(50) AFTER REQUIRE_EMAIL_VERIFICATION;
ALTER TABLE MGT_TENANT_CONFIG ADD COLUMN ONBOARDING_DATE DATE AFTER SUBSCRIPTION_PLAN;
ALTER TABLE MGT_TENANT_CONFIG ADD COLUMN EXPIRATION_DATE DATE AFTER ONBOARDING_DATE;
