-- *******************************************************
-- Script de Refactorización de Administración (SaaS Elite)
-- *******************************************************
-- Transición de Herencia (Joined) a Composición Pura.

-- A. SuperAdmin Refactor
ALTER TABLE MGT_SUPER_ADMIN DROP FOREIGN KEY FK_SUPER_ADMIN_PERSON;
ALTER TABLE MGT_SUPER_ADMIN ADD COLUMN FK_ID_PERSON BIGINT AFTER VERSION;
ALTER TABLE MGT_SUPER_ADMIN ADD COLUMN FK_ID_USER BIGINT AFTER FK_ID_PERSON;

-- Sync data: El ID anterior era el ID de Person
UPDATE MGT_SUPER_ADMIN SET FK_ID_PERSON = ID, FK_ID_USER = USER_ID;

-- Hacer que ID sea un PK independiente
ALTER TABLE MGT_SUPER_ADMIN MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE MGT_SUPER_ADMIN DROP COLUMN USER_ID;

-- Añadir nuevas restricciones
ALTER TABLE MGT_SUPER_ADMIN ADD CONSTRAINT FK_SUPER_ADMIN_PERSON FOREIGN KEY (FK_ID_PERSON) REFERENCES DMN_PERSON(ID);
ALTER TABLE MGT_SUPER_ADMIN ADD CONSTRAINT FK_SUPER_ADMIN_USER FOREIGN KEY (FK_ID_USER) REFERENCES AUT_USER(ID);


-- B. TenantAdmin Refactor
ALTER TABLE MGT_TENANT_ADMIN DROP FOREIGN KEY FK_TENANT_ADMIN_PERSON;
ALTER TABLE MGT_TENANT_ADMIN ADD COLUMN FK_ID_PERSON BIGINT AFTER VERSION;
ALTER TABLE MGT_TENANT_ADMIN ADD COLUMN FK_ID_USER BIGINT AFTER FK_ID_PERSON;

-- Sync data
UPDATE MGT_TENANT_ADMIN SET FK_ID_PERSON = ID, FK_ID_USER = USER_ID;

-- Hacer que ID sea un PK independiente
ALTER TABLE MGT_TENANT_ADMIN MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE MGT_TENANT_ADMIN DROP COLUMN USER_ID;

-- Añadir nuevas restricciones
ALTER TABLE MGT_TENANT_ADMIN ADD CONSTRAINT FK_TENANT_ADMIN_PERSON FOREIGN KEY (FK_ID_PERSON) REFERENCES DMN_PERSON(ID);
ALTER TABLE MGT_TENANT_ADMIN ADD CONSTRAINT FK_TENANT_ADMIN_USER FOREIGN KEY (FK_ID_USER) REFERENCES AUT_USER(ID);
