/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Kinship } from '../../models/kinship';

export interface CreateKinship$Params {
      body: Kinship
}

export function createKinship(http: HttpClient, rootUrl: string, params: CreateKinship$Params, context?: HttpContext): Observable<StrictHttpResponse<Kinship>> {
  const rb = new RequestBuilder(rootUrl, createKinship.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Kinship>;
    })
  );
}

createKinship.PATH = '/mdm/kinship';
