/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Kinship } from '../../models/kinship';

export interface GetKinshipById$Params {

/**
 * ID del Kinship a recuperar
 */
  id: number;
}

export function getKinshipById(http: HttpClient, rootUrl: string, params: GetKinshipById$Params, context?: HttpContext): Observable<StrictHttpResponse<Kinship>> {
  const rb = new RequestBuilder(rootUrl, getKinshipById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Kinship>;
    })
  );
}

getKinshipById.PATH = '/mdm/kinship/{id}';
