-- ============================================================
-- Script: V9_20__create_demographic.sql
-- Módulo: vitalia-medical-catalog
-- Descripción: Creación de CAT_GENDER y CAT_CIVIL_STATUS.
-- Autor: Juan Amachi
-- Fecha: 2026-01-04
-- ============================================================

-- Tabla CAT_GENDER
CREATE TABLE IF NOT EXISTS CAT_GENDER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    CONSTRAINT UK_GENDER_CODE UNIQUE (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla CAT_CIVIL_STATUS
CREATE TABLE IF NOT EXISTS CAT_CIVIL_STATUS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    CONSTRAINT UK_CIVIL_STATUS_CODE UNIQUE (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
