-- ============================================================
-- Script: V9_1__insert_icd10.sql
-- Módulo: vitalia-medical-catalog
-- Descripción: Inserción de datos estándar CAT_ICD10 (Extendido).
-- ============================================================

INSERT INTO CAT_ICD10 (CODE, DESCRIPTION, CREATED_BY, CREATED_DATE) VALUES
('A00', 'Cólera', 'SYSTEM', CURRENT_TIMESTAMP),
('A01', 'Fiebres tifoidea y paratifoidea', 'SYSTEM', CURRENT_TIMESTAMP),
('A02', 'Otras salmonelosis', 'SYSTEM', CURRENT_TIMESTAMP),
('A03', 'Shigelosis', 'SYSTEM', CURRENT_TIMESTAMP),
('A04', 'Otras infecciones intestinales bacterianas', 'SYSTEM', CURRENT_TIMESTAMP),
('A05', 'Otras intoxicaciones alimentarias bacterianas', 'SYSTEM', CURRENT_TIMESTAMP),
('A06', 'Amebiasis', 'SYSTEM', CURRENT_TIMESTAMP),
('A09', 'Diarrea y gastroenteritis de presunto origen infeccioso', 'SYSTEM', CURRENT_TIMESTAMP),
('A15', 'Tuberculosis respiratoria, confirmada', 'SYSTEM', CURRENT_TIMESTAMP),
('A16', 'Tuberculosis respiratoria, no confirmada', 'SYSTEM', CURRENT_TIMESTAMP),
('A17', 'Tuberculosis del sistema nervioso', 'SYSTEM', CURRENT_TIMESTAMP),
('A18', 'Tuberculosis de otros órganos', 'SYSTEM', CURRENT_TIMESTAMP),
('A30', 'Lepra [enfermedad de Hansen]', 'SYSTEM', CURRENT_TIMESTAMP),
('A37', 'Tos ferina [tos paroxística]', 'SYSTEM', CURRENT_TIMESTAMP),
('A39', 'Infección meningocócica', 'SYSTEM', CURRENT_TIMESTAMP),
('A40', 'Septicemia estreptocócica', 'SYSTEM', CURRENT_TIMESTAMP),
('A41', 'Otras septicemias', 'SYSTEM', CURRENT_TIMESTAMP),
('A46', 'Erisipela', 'SYSTEM', CURRENT_TIMESTAMP),
('A50', 'Sífilis congénita', 'SYSTEM', CURRENT_TIMESTAMP),
('A51', 'Sífilis precoz', 'SYSTEM', CURRENT_TIMESTAMP),
('A53', 'Otras sífilis y las no especificadas', 'SYSTEM', CURRENT_TIMESTAMP),
('A54', 'Infección gonocócica', 'SYSTEM', CURRENT_TIMESTAMP),
('A60', 'Infección anogenital debida a virus del herpes simple', 'SYSTEM', CURRENT_TIMESTAMP),
('B01', 'Varicela', 'SYSTEM', CURRENT_TIMESTAMP),
('B02', 'Herpes zoster', 'SYSTEM', CURRENT_TIMESTAMP),
('B05', 'Sarampión', 'SYSTEM', CURRENT_TIMESTAMP),
('B06', 'Rubéola [sarampión alemán]', 'SYSTEM', CURRENT_TIMESTAMP),
('B15', 'Hepatitis aguda tipo A', 'SYSTEM', CURRENT_TIMESTAMP),
('B16', 'Hepatitis aguda tipo B', 'SYSTEM', CURRENT_TIMESTAMP),
('B17', 'Otras hepatitis virales agudas', 'SYSTEM', CURRENT_TIMESTAMP),
('B18', 'Hepatitis viral crónica', 'SYSTEM', CURRENT_TIMESTAMP),
('B20', 'Enfermedad por VIH, con enfermedades infecciosas', 'SYSTEM', CURRENT_TIMESTAMP),
('B24', 'Enfermedad por VIH, sin especificación', 'SYSTEM', CURRENT_TIMESTAMP),
('B26', 'Parotiditis infecciosa', 'SYSTEM', CURRENT_TIMESTAMP),
('B35', 'Dermatofitosis', 'SYSTEM', CURRENT_TIMESTAMP),
('B37', 'Candidiasis', 'SYSTEM', CURRENT_TIMESTAMP),
('B50', 'Paludismo por Plasmodium falciparum', 'SYSTEM', CURRENT_TIMESTAMP),
('C00', 'Tumor maligno del labio', 'SYSTEM', CURRENT_TIMESTAMP),
('C02', 'Tumor maligno de otras partes de la lengua', 'SYSTEM', CURRENT_TIMESTAMP),
('C15', 'Tumor maligno del esófago', 'SYSTEM', CURRENT_TIMESTAMP),
('C16', 'Tumor maligno del estómago', 'SYSTEM', CURRENT_TIMESTAMP),
('C18', 'Tumor maligno del colon', 'SYSTEM', CURRENT_TIMESTAMP),
('C19', 'Tumor maligno de la unión rectosigmoidea', 'SYSTEM', CURRENT_TIMESTAMP),
('C20', 'Tumor maligno del recto', 'SYSTEM', CURRENT_TIMESTAMP),
('C22', 'Tumor maligno del hígado', 'SYSTEM', CURRENT_TIMESTAMP),
('C25', 'Tumor maligno del páncreas', 'SYSTEM', CURRENT_TIMESTAMP),
('C34', 'Tumor maligno de los bronquios y del pulmón', 'SYSTEM', CURRENT_TIMESTAMP),
('C43', 'Melanoma maligno de la piel', 'SYSTEM', CURRENT_TIMESTAMP),
('C44', 'Otros tumores malignos de la piel', 'SYSTEM', CURRENT_TIMESTAMP),
('C50', 'Tumor maligno de la mama', 'SYSTEM', CURRENT_TIMESTAMP),
('C53', 'Tumor maligno del cuello del útero', 'SYSTEM', CURRENT_TIMESTAMP),
('C56', 'Tumor maligno del ovario', 'SYSTEM', CURRENT_TIMESTAMP),
('C61', 'Tumor maligno de la próstata', 'SYSTEM', CURRENT_TIMESTAMP),
('C64', 'Tumor maligno del riñón', 'SYSTEM', CURRENT_TIMESTAMP),
('C67', 'Tumor maligno de la vejiga urinaria', 'SYSTEM', CURRENT_TIMESTAMP),
('C71', 'Tumor maligno del encéfalo', 'SYSTEM', CURRENT_TIMESTAMP),
('C81', 'Enfermedad de Hodgkin', 'SYSTEM', CURRENT_TIMESTAMP),
('C82', 'Linfoma no Hodgkin folicular', 'SYSTEM', CURRENT_TIMESTAMP),
('C85', 'Linfoma no Hodgkin, no especificado', 'SYSTEM', CURRENT_TIMESTAMP),
('C91', 'Leucemia linfoide', 'SYSTEM', CURRENT_TIMESTAMP),
('C92', 'Leucemia mieloide', 'SYSTEM', CURRENT_TIMESTAMP),
('D50', 'Anemia por deficiencia de hierro', 'SYSTEM', CURRENT_TIMESTAMP),
('D51', 'Anemia por deficiencia de vitamina B12', 'SYSTEM', CURRENT_TIMESTAMP),
('D64', 'Otras anemias', 'SYSTEM', CURRENT_TIMESTAMP),
('E03', 'Otros hipotiroidismos', 'SYSTEM', CURRENT_TIMESTAMP),
('E04', 'Otro bocio no tóxico', 'SYSTEM', CURRENT_TIMESTAMP),
('E05', 'Tirotoxicosis [hipertiroidismo]', 'SYSTEM', CURRENT_TIMESTAMP),
('E06', 'Tiroiditis', 'SYSTEM', CURRENT_TIMESTAMP),
('E10', 'Diabetes mellitus insulinodependiente', 'SYSTEM', CURRENT_TIMESTAMP),
('E11', 'Diabetes mellitus no insulinodependiente', 'SYSTEM', CURRENT_TIMESTAMP),
('E14', 'Diabetes mellitus, no especificada', 'SYSTEM', CURRENT_TIMESTAMP),
('E66', 'Obesidad', 'SYSTEM', CURRENT_TIMESTAMP),
('E78', 'Trastornos del metabolismo de las lipoproteínas', 'SYSTEM', CURRENT_TIMESTAMP),
('F03', 'Demencia, no especificada', 'SYSTEM', CURRENT_TIMESTAMP),
('F10', 'Trastornos mentales debidos al uso de alcohol', 'SYSTEM', CURRENT_TIMESTAMP),
('F17', 'Trastornos mentales debidos al uso de tabaco', 'SYSTEM', CURRENT_TIMESTAMP),
('F20', 'Esquizofrenia', 'SYSTEM', CURRENT_TIMESTAMP),
('F31', 'Trastorno afectivo bipolar', 'SYSTEM', CURRENT_TIMESTAMP),
('F32', 'Episodio depresivo', 'SYSTEM', CURRENT_TIMESTAMP),
('F41', 'Otros trastornos de ansiedad', 'SYSTEM', CURRENT_TIMESTAMP),
('G00', 'Meningitis bacteriana', 'SYSTEM', CURRENT_TIMESTAMP),
('G20', 'Enfermedad de Parkinson', 'SYSTEM', CURRENT_TIMESTAMP),
('G30', 'Enfermedad de Alzheimer', 'SYSTEM', CURRENT_TIMESTAMP),
('G40', 'Epilepsia', 'SYSTEM', CURRENT_TIMESTAMP),
('G43', 'Migraña', 'SYSTEM', CURRENT_TIMESTAMP),
('G44', 'Otros síndromes de cefalea', 'SYSTEM', CURRENT_TIMESTAMP),
('H10', 'Conjuntivitis', 'SYSTEM', CURRENT_TIMESTAMP),
('H25', 'Catarata senil', 'SYSTEM', CURRENT_TIMESTAMP),
('H40', 'Glaucoma', 'SYSTEM', CURRENT_TIMESTAMP),
('H65', 'Otitis media no supurativa', 'SYSTEM', CURRENT_TIMESTAMP),
('H66', 'Otitis media supurativa', 'SYSTEM', CURRENT_TIMESTAMP),
('I10', 'Hipertensión esencial (primaria)', 'SYSTEM', CURRENT_TIMESTAMP),
('I11', 'Enfermedad cardíaca hipertensiva', 'SYSTEM', CURRENT_TIMESTAMP),
('I20', 'Angina de pecho', 'SYSTEM', CURRENT_TIMESTAMP),
('I21', 'Infarto agudo del miocardio', 'SYSTEM', CURRENT_TIMESTAMP),
('I25', 'Enfermedad isquémica crónica del corazón', 'SYSTEM', CURRENT_TIMESTAMP),
('I42', 'Cardiomiopatía', 'SYSTEM', CURRENT_TIMESTAMP),
('I48', 'Fibrilación y aleteo auricular', 'SYSTEM', CURRENT_TIMESTAMP),
('I50', 'Insuficiencia cardíaca', 'SYSTEM', CURRENT_TIMESTAMP),
('I61', 'Hemorragia intraencefálica', 'SYSTEM', CURRENT_TIMESTAMP),
('I63', 'Infarto cerebral', 'SYSTEM', CURRENT_TIMESTAMP),
('I64', 'Accidente vascular encefálico agudo', 'SYSTEM', CURRENT_TIMESTAMP),
('I80', 'Flebitis y tromboflebitis', 'SYSTEM', CURRENT_TIMESTAMP),
('I83', 'Venas varicosas de las extremidades inferiores', 'SYSTEM', CURRENT_TIMESTAMP),
('I84', 'Hemorroides', 'SYSTEM', CURRENT_TIMESTAMP),
('J00', 'Rinofaringitis aguda [resfriado común]', 'SYSTEM', CURRENT_TIMESTAMP),
('J01', 'Sinusitis aguda', 'SYSTEM', CURRENT_TIMESTAMP),
('J02', 'Faringitis aguda', 'SYSTEM', CURRENT_TIMESTAMP),
('J03', 'Amigdalitis aguda', 'SYSTEM', CURRENT_TIMESTAMP),
('J04', 'Laringitis y traqueítis agudas', 'SYSTEM', CURRENT_TIMESTAMP),
('J06', 'Infecciones agudas de las vías superiores', 'SYSTEM', CURRENT_TIMESTAMP),
('J11', 'Influenza, virus no identificado', 'SYSTEM', CURRENT_TIMESTAMP),
('J18', 'Neumonía, organismo no especificado', 'SYSTEM', CURRENT_TIMESTAMP),
('J20', 'Bronquitis aguda', 'SYSTEM', CURRENT_TIMESTAMP),
('J30', 'Rinitis alérgica y vasomotora', 'SYSTEM', CURRENT_TIMESTAMP),
('J31', 'Rinitis, rinofaringitis y faringitis crónicas', 'SYSTEM', CURRENT_TIMESTAMP),
('J32', 'Sinusitis crónica', 'SYSTEM', CURRENT_TIMESTAMP),
('J35', 'Enfermedades crónicas de las amígdalas y de las adenoides', 'SYSTEM', CURRENT_TIMESTAMP),
('J44', 'Otras enfermedades pulmonares obstructivas crónicas', 'SYSTEM', CURRENT_TIMESTAMP),
('J45', 'Asma', 'SYSTEM', CURRENT_TIMESTAMP),
('K21', 'Enfermedad del reflujo gastroesofágico', 'SYSTEM', CURRENT_TIMESTAMP),
('K25', 'Úlcera gástrica', 'SYSTEM', CURRENT_TIMESTAMP),
('K29', 'Gastritis y duodenitis', 'SYSTEM', CURRENT_TIMESTAMP),
('K35', 'Apendicitis aguda', 'SYSTEM', CURRENT_TIMESTAMP),
('K40', 'Hernia inguinal', 'SYSTEM', CURRENT_TIMESTAMP),
('K52', 'Otras gastroenteritis y colitis no infecciosas', 'SYSTEM', CURRENT_TIMESTAMP),
('K59', 'Trastornos funcionales del intestino', 'SYSTEM', CURRENT_TIMESTAMP),
('K80', 'Colelitiasis', 'SYSTEM', CURRENT_TIMESTAMP),
('K81', 'Colecistitis', 'SYSTEM', CURRENT_TIMESTAMP),
('L03', 'Celulitis', 'SYSTEM', CURRENT_TIMESTAMP),
('L20', 'Dermatitis atópica', 'SYSTEM', CURRENT_TIMESTAMP),
('L40', 'Psoriasis', 'SYSTEM', CURRENT_TIMESTAMP),
('L70', 'Acné', 'SYSTEM', CURRENT_TIMESTAMP),
('M10', 'Gota', 'SYSTEM', CURRENT_TIMESTAMP),
('M13', 'Otras artritis', 'SYSTEM', CURRENT_TIMESTAMP),
('M17', 'Osteoartritis de la rodilla [gonartrosis]', 'SYSTEM', CURRENT_TIMESTAMP),
('M19', 'Otras artrosis', 'SYSTEM', CURRENT_TIMESTAMP),
('M51', 'Otros trastornos de los discos intervertebrales', 'SYSTEM', CURRENT_TIMESTAMP),
('M54', 'Dorsalgia', 'SYSTEM', CURRENT_TIMESTAMP),
('M62', 'Otros trastornos de los músculos', 'SYSTEM', CURRENT_TIMESTAMP),
('M81', 'Osteoporosis sin fractura patológica', 'SYSTEM', CURRENT_TIMESTAMP),
('N10', 'Nefritis túbulo-intersticial aguda', 'SYSTEM', CURRENT_TIMESTAMP),
('N18', 'Enfermedad renal crónica', 'SYSTEM', CURRENT_TIMESTAMP),
('N20', 'Calculosis del riñón y del uréter', 'SYSTEM', CURRENT_TIMESTAMP),
('N30', 'Cistitis', 'SYSTEM', CURRENT_TIMESTAMP),
('N39', 'Otros trastornos del sistema urinario', 'SYSTEM', CURRENT_TIMESTAMP),
('N40', 'Hiperplasia de la próstata', 'SYSTEM', CURRENT_TIMESTAMP),
('N60', 'Displasia mamaria benigna', 'SYSTEM', CURRENT_TIMESTAMP),
('N70', 'Salpingitis y ooforitis', 'SYSTEM', CURRENT_TIMESTAMP),
('N73', 'Otras enfermedades pélvicas inflamatorias femeninas', 'SYSTEM', CURRENT_TIMESTAMP),
('N76', 'Otras inflamaciones de la vagina y de la vulva', 'SYSTEM', CURRENT_TIMESTAMP),
('N91', 'Menstruación ausente, escasa o rara', 'SYSTEM', CURRENT_TIMESTAMP),
('N92', 'Menstruación excesiva, frecuente e irregular', 'SYSTEM', CURRENT_TIMESTAMP),
('N95', 'Trastornos de la menopausia y otros trastornos perimenopáusicos', 'SYSTEM', CURRENT_TIMESTAMP),
('O80', 'Parto único espontáneo', 'SYSTEM', CURRENT_TIMESTAMP),
('P07', 'Trastornos relacionados con duración corta de la gestación', 'SYSTEM', CURRENT_TIMESTAMP),
('Q05', 'Espina bífida', 'SYSTEM', CURRENT_TIMESTAMP),
('R05', 'Tos', 'SYSTEM', CURRENT_TIMESTAMP),
('R07', 'Dolor en el pecho', 'SYSTEM', CURRENT_TIMESTAMP),
('R10', 'Dolor abdominal y pélvico', 'SYSTEM', CURRENT_TIMESTAMP),
('R11', 'Náusea y vómito', 'SYSTEM', CURRENT_TIMESTAMP),
('R42', 'Mareo y desvanecimiento', 'SYSTEM', CURRENT_TIMESTAMP),
('R50', 'Fiebre de origen desconocido', 'SYSTEM', CURRENT_TIMESTAMP),
('R51', 'Cefalea', 'SYSTEM', CURRENT_TIMESTAMP),
('R60', 'Edema, no clasificado en otra parte', 'SYSTEM', CURRENT_TIMESTAMP),
('S00', 'Traumatismo superficial de la cabeza', 'SYSTEM', CURRENT_TIMESTAMP),
('S01', 'Herida de la cabeza', 'SYSTEM', CURRENT_TIMESTAMP),
('S06', 'Traumatismo intracraneal', 'SYSTEM', CURRENT_TIMESTAMP),
('S52', 'Fractura del antebrazo', 'SYSTEM', CURRENT_TIMESTAMP),
('S72', 'Fractura del fémur', 'SYSTEM', CURRENT_TIMESTAMP),
('S82', 'Fractura de la pierna, inclusive el tobillo', 'SYSTEM', CURRENT_TIMESTAMP),
('S93', 'Luxación, esguince y torcedura del tobillo y del pie', 'SYSTEM', CURRENT_TIMESTAMP),
('T00', 'Traumatismos superficiales que afectan múltiples regiones del cuerpo', 'SYSTEM', CURRENT_TIMESTAMP),
('T14', 'Traumatismo de región no especificada del cuerpo', 'SYSTEM', CURRENT_TIMESTAMP),
('U07', 'Uso emergente de U07 (COVID-19)', 'SYSTEM', CURRENT_TIMESTAMP),
('Z00', 'Examen general y de investigación de personas sin quejas', 'SYSTEM', CURRENT_TIMESTAMP),
('Z01', 'Otros exámenes especiales e investigaciones de personas sin quejas', 'SYSTEM', CURRENT_TIMESTAMP),
('Z30', 'Atención para la anticoncepción', 'SYSTEM', CURRENT_TIMESTAMP),
('Z34', 'Supervisión de embarazo normal', 'SYSTEM', CURRENT_TIMESTAMP);
