-- ============================================================
-- Script: V9_21__create_cat_demographic.sql
-- Módulo: vitalia-medical-catalog
-- Descripción: Creación de CAT_GENDER y CAT_CIVIL_STATUS (SaaS Elite Tier).
-- Autor: Juan Amachi
-- Fecha: 2026-01-04
-- ============================================================

-- Tabla CAT_GENDER
CREATE TABLE IF NOT EXISTS CAT_GENDER (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID   VARCHAR(50)  NOT NULL,
    EXTERNAL_ID VARCHAR(36)  NOT NULL,
    CODE        VARCHAR(20)  NOT NULL,
    NAME        VARCHAR(50)  NOT NULL,
    ACTIVE      BOOLEAN      NOT NULL DEFAULT TRUE,
    VERSION     BIGINT       NOT NULL DEFAULT 0,

    -- Auditoría
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP    NOT NULL,
    LAST_MODIFIED_BY  VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_GENDER_EXTERNAL_ID UNIQUE (EXTERNAL_ID),
    CONSTRAINT UK_GENDER_CODE_TENANT UNIQUE (CODE, TENANT_ID),
    INDEX IDX_GENDER_TENANT (TENANT_ID),
    INDEX IDX_GENDER_CODE   (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla CAT_CIVIL_STATUS
CREATE TABLE IF NOT EXISTS CAT_CIVIL_STATUS (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID   VARCHAR(50)  NOT NULL,
    EXTERNAL_ID VARCHAR(36)  NOT NULL,
    CODE        VARCHAR(20)  NOT NULL,
    NAME        VARCHAR(50)  NOT NULL,
    ACTIVE      BOOLEAN      NOT NULL DEFAULT TRUE,
    VERSION     BIGINT       NOT NULL DEFAULT 0,

    -- Auditoría
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP    NOT NULL,
    LAST_MODIFIED_BY  VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_CIVIL_STATUS_EXTERNAL_ID UNIQUE (EXTERNAL_ID),
    CONSTRAINT UK_CIVIL_STATUS_CODE_TENANT UNIQUE (CODE, TENANT_ID),
    INDEX IDX_CIVIL_STATUS_TENANT (TENANT_ID),
    INDEX IDX_CIVIL_STATUS_CODE   (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
