-- ============================================================
-- Script: V9_1__insert_icd10.sql
-- Módulo: vitalia-medical-catalog
-- Descripción: Inserción de datos estándar CAT_ICD10 (Extendido).
-- ============================================================

INSERT INTO CAT_ICD10 (CODE, DESCRIPTION, CREATED_BY) VALUES
('A00', 'Cólera', 'SYSTEM'), ('A01', 'Fiebres tifoidea y paratifoidea', 'SYSTEM'), ('A02', 'Otras salmonelosis', 'SYSTEM'), ('A03', 'Shigelosis', 'SYSTEM'),
('A04', 'Otras infecciones intestinales bacterianas', 'SYSTEM'), ('A05', 'Otras intoxicaciones alimentarias bacterianas', 'SYSTEM'), ('A06', 'Amebiasis', 'SYSTEM'),
('A09', 'Diarrea y gastroenteritis de presunto origen infeccioso', 'SYSTEM'), ('A15', 'Tuberculosis respiratoria, confirmada', 'SYSTEM'), ('A16', 'Tuberculosis respiratoria, no confirmada', 'SYSTEM'),
('A17', 'Tuberculosis del sistema nervioso', 'SYSTEM'), ('A18', 'Tuberculosis de otros órganos', 'SYSTEM'), ('A30', 'Lepra [enfermedad de Hansen]', 'SYSTEM'),
('A37', 'Tos ferina [tos paroxística]', 'SYSTEM'), ('A39', 'Infección meningocócica', 'SYSTEM'), ('A40', 'Septicemia estreptocócica', 'SYSTEM'),
('A41', 'Otras septicemias', 'SYSTEM'), ('A46', 'Erisipela', 'SYSTEM'), ('A50', 'Sífilis congénita', 'SYSTEM'), ('A51', 'Sífilis precoz', 'SYSTEM'),
('A53', 'Otras sífilis y las no especificadas', 'SYSTEM'), ('A54', 'Infección gonocócica', 'SYSTEM'), ('A60', 'Infección anogenital debida a virus del herpes simple', 'SYSTEM'),
('B01', 'Varicela', 'SYSTEM'), ('B02', 'Herpes zoster', 'SYSTEM'), ('B05', 'Sarampión', 'SYSTEM'), ('B06', 'Rubéola [sarampión alemán]', 'SYSTEM'),
('B15', 'Hepatitis aguda tipo A', 'SYSTEM'), ('B16', 'Hepatitis aguda tipo B', 'SYSTEM'), ('B17', 'Otras hepatitis virales agudas', 'SYSTEM'),
('B18', 'Hepatitis viral crónica', 'SYSTEM'), ('B20', 'Enfermedad por VIH, con enfermedades infecciosas', 'SYSTEM'), ('B24', 'Enfermedad por VIH, sin especificación', 'SYSTEM'),
('B26', 'Parotiditis infecciosa', 'SYSTEM'), ('B35', 'Dermatofitosis', 'SYSTEM'), ('B37', 'Candidiasis', 'SYSTEM'),
('B50', 'Paludismo por Plasmodium falciparum', 'SYSTEM'), ('C00', 'Tumor maligno del labio', 'SYSTEM'), ('C02', 'Tumor maligno de otras partes de la lengua', 'SYSTEM'),
('C15', 'Tumor maligno del esófago', 'SYSTEM'), ('C16', 'Tumor maligno del estómago', 'SYSTEM'), ('C18', 'Tumor maligno del colon', 'SYSTEM'),
('C19', 'Tumor maligno de la unión rectosigmoidea', 'SYSTEM'), ('C20', 'Tumor maligno del recto', 'SYSTEM'), ('C22', 'Tumor maligno del hígado', 'SYSTEM'),
('C25', 'Tumor maligno del páncreas', 'SYSTEM'), ('C34', 'Tumor maligno de los bronquios y del pulmón', 'SYSTEM'), ('C43', 'Melanoma maligno de la piel', 'SYSTEM'),
('C44', 'Otros tumores malignos de la piel', 'SYSTEM'), ('C50', 'Tumor maligno de la mama', 'SYSTEM'), ('C53', 'Tumor maligno del cuello del útero', 'SYSTEM'),
('C56', 'Tumor maligno del ovario', 'SYSTEM'), ('C61', 'Tumor maligno de la próstata', 'SYSTEM'), ('C64', 'Tumor maligno del riñón', 'SYSTEM'),
('C67', 'Tumor maligno de la vejiga urinaria', 'SYSTEM'), ('C71', 'Tumor maligno del encéfalo', 'SYSTEM'), ('C81', 'Enfermedad de Hodgkin', 'SYSTEM'),
('C82', 'Linfoma no Hodgkin folicular', 'SYSTEM'), ('C85', 'Linfoma no Hodgkin, no especificado', 'SYSTEM'), ('C91', 'Leucemia linfoide', 'SYSTEM'),
('C92', 'Leucemia mieloide', 'SYSTEM'), ('D50', 'Anemia por deficiencia de hierro', 'SYSTEM'), ('D51', 'Anemia por deficiencia de vitamina B12', 'SYSTEM'),
('D64', 'Otras anemias', 'SYSTEM'), ('E03', 'Otros hipotiroidismos', 'SYSTEM'), ('E04', 'Otro bocio no tóxico', 'SYSTEM'),
('E05', 'Tirotoxicosis [hipertiroidismo]', 'SYSTEM'), ('E06', 'Tiroiditis', 'SYSTEM'), ('E10', 'Diabetes mellitus insulinodependiente', 'SYSTEM'),
('E11', 'Diabetes mellitus no insulinodependiente', 'SYSTEM'), ('E14', 'Diabetes mellitus, no especificada', 'SYSTEM'), ('E66', 'Obesidad', 'SYSTEM'),
('E78', 'Trastornos del metabolismo de las lipoproteínas', 'SYSTEM'), ('F03', 'Demencia, no especificada', 'SYSTEM'), ('F10', 'Trastornos mentales debidos al uso de alcohol', 'SYSTEM'),
('F17', 'Trastornos mentales debidos al uso de tabaco', 'SYSTEM'), ('F20', 'Esquizofrenia', 'SYSTEM'), ('F31', 'Trastorno afectivo bipolar', 'SYSTEM'),
('F32', 'Episodio depresivo', 'SYSTEM'), ('F41', 'Otros trastornos de ansiedad', 'SYSTEM'), ('G00', 'Meningitis bacteriana', 'SYSTEM'),
('G20', 'Enfermedad de Parkinson', 'SYSTEM'), ('G30', 'Enfermedad de Alzheimer', 'SYSTEM'), ('G40', 'Epilepsia', 'SYSTEM'),
('G43', 'Migraña', 'SYSTEM'), ('G44', 'Otros síndromes de cefalea', 'SYSTEM'), ('H10', 'Conjuntivitis', 'SYSTEM'),
('H25', 'Catarata senil', 'SYSTEM'), ('H40', 'Glaucoma', 'SYSTEM'), ('H65', 'Otitis media no supurativa', 'SYSTEM'),
('H66', 'Otitis media supurativa', 'SYSTEM'), ('I10', 'Hipertensión esencial (primaria)', 'SYSTEM'), ('I11', 'Enfermedad cardíaca hipertensiva', 'SYSTEM'),
('I20', 'Angina de pecho', 'SYSTEM'), ('I21', 'Infarto agudo del miocardio', 'SYSTEM'), ('I25', 'Enfermedad isquémica crónica del corazón', 'SYSTEM'),
('I42', 'Cardiomiopatía', 'SYSTEM'), ('I48', 'Fibrilación y aleteo auricular', 'SYSTEM'), ('I50', 'Insuficiencia cardíaca', 'SYSTEM'),
('I61', 'Hemorragia intraencefálica', 'SYSTEM'), ('I63', 'Infarto cerebral', 'SYSTEM'), ('I64', 'Accidente vascular encefálico agudo', 'SYSTEM'),
('I80', 'Flebitis y tromboflebitis', 'SYSTEM'), ('I83', 'Venas varicosas de las extremidades inferiores', 'SYSTEM'), ('I84', 'Hemorroides', 'SYSTEM'),
('J00', 'Rinofaringitis aguda [resfriado común]', 'SYSTEM'), ('J01', 'Sinusitis aguda', 'SYSTEM'), ('J02', 'Faringitis aguda', 'SYSTEM'),
('J03', 'Amigdalitis aguda', 'SYSTEM'), ('J04', 'Laringitis y traqueítis agudas', 'SYSTEM'), ('J06', 'Infecciones agudas de las vías superiores', 'SYSTEM'),
('J11', 'Influenza, virus no identificado', 'SYSTEM'), ('J18', 'Neumonía, organismo no especificado', 'SYSTEM'), ('J20', 'Bronquitis aguda', 'SYSTEM'),
('J30', 'Rinitis alérgica y vasomotora', 'SYSTEM'), ('J31', 'Rinitis, rinofaringitis y faringitis crónicas', 'SYSTEM'), ('J32', 'Sinusitis crónica', 'SYSTEM'),
('J35', 'Enfermedades crónicas de las amígdalas y de las adenoides', 'SYSTEM'), ('J44', 'Otras enfermedades pulmonares obstructivas crónicas', 'SYSTEM'), ('J45', 'Asma', 'SYSTEM'),
('K21', 'Enfermedad del reflujo gastroesofágico', 'SYSTEM'), ('K25', 'Úlcera gástrica', 'SYSTEM'), ('K29', 'Gastritis y duodenitis', 'SYSTEM'),
('K35', 'Apendicitis aguda', 'SYSTEM'), ('K40', 'Hernia inguinal', 'SYSTEM'), ('K52', 'Otras gastroenteritis y colitis no infecciosas', 'SYSTEM'),
('K59', 'Trastornos funcionales del intestino', 'SYSTEM'), ('K80', 'Colelitiasis', 'SYSTEM'), ('K81', 'Colecistitis', 'SYSTEM'),
('L03', 'Celulitis', 'SYSTEM'), ('L20', 'Dermatitis atópica', 'SYSTEM'), ('L40', 'Psoriasis', 'SYSTEM'),
('L70', 'Acné', 'SYSTEM'), ('M10', 'Gota', 'SYSTEM'), ('M13', 'Otras artritis', 'SYSTEM'),
('M17', 'Osteoartritis de la rodilla [gonartrosis]', 'SYSTEM'), ('M19', 'Otras artrosis', 'SYSTEM'), ('M51', 'Otros trastornos de los discos intervertebrales', 'SYSTEM'),
('M54', 'Dorsalgia', 'SYSTEM'), ('M62', 'Otros trastornos de los músculos', 'SYSTEM'), ('M81', 'Osteoporosis sin fractura patológica', 'SYSTEM'),
('N10', 'Nefritis túbulo-intersticial aguda', 'SYSTEM'), ('N18', 'Enfermedad renal crónica', 'SYSTEM'), ('N20', 'Calculosis del riñón y del uréter', 'SYSTEM'),
('N30', 'Cistitis', 'SYSTEM'), ('N39', 'Otros trastornos del sistema urinario', 'SYSTEM'), ('N40', 'Hiperplasia de la próstata', 'SYSTEM'),
('N60', 'Displasia mamaria benigna', 'SYSTEM'), ('N70', 'Salpingitis y ooforitis', 'SYSTEM'), ('N73', 'Otras enfermedades pélvicas inflamatorias femeninas', 'SYSTEM'),
('N76', 'Otras inflamaciones de la vagina y de la vulva', 'SYSTEM'), ('N91', 'Menstruación ausente, escasa o rara', 'SYSTEM'), ('N92', 'Menstruación excesiva, frecuente e irregular', 'SYSTEM'),
('N95', 'Trastornos de la menopausia y otros trastornos perimenopáusicos', 'SYSTEM'), ('O80', 'Parto único espontáneo', 'SYSTEM'), ('P07', 'Trastornos relacionados con duración corta de la gestación', 'SYSTEM'),
('Q05', 'Espina bífida', 'SYSTEM'), ('R05', 'Tos', 'SYSTEM'), ('R07', 'Dolor en el pecho', 'SYSTEM'),
('R10', 'Dolor abdominal y pélvico', 'SYSTEM'), ('R11', 'Náusea y vómito', 'SYSTEM'), ('R42', 'Mareo y desvanecimiento', 'SYSTEM'),
('R50', 'Fiebre de origen desconocido', 'SYSTEM'), ('R51', 'Cefalea', 'SYSTEM'), ('R60', 'Edema, no clasificado en otra parte', 'SYSTEM'),
('S00', 'Traumatismo superficial de la cabeza', 'SYSTEM'), ('S01', 'Herida de la cabeza', 'SYSTEM'), ('S06', 'Traumatismo intracraneal', 'SYSTEM'),
('S52', 'Fractura del antebrazo', 'SYSTEM'), ('S72', 'Fractura del fémur', 'SYSTEM'), ('S82', 'Fractura de la pierna, inclusive el tobillo', 'SYSTEM'),
('S93', 'Luxación, esguince y torcedura del tobillo y del pie', 'SYSTEM'), ('T00', 'Traumatismos superficiales que afectan múltiples regiones del cuerpo', 'SYSTEM'), ('T14', 'Traumatismo de región no especificada del cuerpo', 'SYSTEM'),
('U07', 'Uso emergente de U07 (COVID-19)', 'SYSTEM'), ('Z00', 'Examen general y de investigación de personas sin quejas', 'SYSTEM'),
('Z01', 'Otros exámenes especiales e investigaciones de personas sin quejas', 'SYSTEM'), ('Z30', 'Atención para la anticoncepción', 'SYSTEM'), ('Z34', 'Supervisión de embarazo normal', 'SYSTEM');
