-- *******************************************************
-- Script de creación de tabla CLI_EMPLOYEE
-- *******************************************************

CREATE TABLE IF NOT EXISTS CLI_EMPLOYEE (
    ID BIGINT PRIMARY KEY,
    EMPLOYEE_TYPE ENUM('ADMINISTRATIVO','MEDICO','ENFERMERO','TECNICO','LABORATORISTA', 'FARMACEUTICO', 'OTRO') NOT NULL,
    EMPLOYEE_STATUS ENUM('ACTIVO','INACTIVO','SUSPENDIDO','LICENCIA','BAJA') NOT NULL,
    PROFESION VARCHAR(150),
    PUESTO VARCHAR(120),
    CARGO VARCHAR(120),
    NRO_COLEGIO_MEDICO VARCHAR(50),
    MATRICULA_PROFESIONAL VARCHAR(50),
    CODIGO_EMPLEADO VARCHAR(20),
    FECHA_INGRESO DATE,
    FECHA_SALIDA DATE,
    FK_ID_USER BIGINT,
    CONSTRAINT FK_CLI_EMPLOYEE_PERSON FOREIGN KEY (ID) REFERENCES DMN_PERSON(ID),
    CONSTRAINT FK_CLI_EMPLOYEE_USER FOREIGN KEY (FK_ID_USER) REFERENCES AUT_USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
