/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del Allergy a crear.
 */
export interface Allergy {
  active?: boolean;
  code: string;
  description?: string;
  id?: number;
  name: string;
  type: string;
}
