/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del Blood Type a crear.
 */
export interface BloodType {

  /**
   * Status
   */
  active?: boolean;

  /**
   * Blood Type Code
   */
  code: string;

  /**
   * Identificador único
   */
  id?: number;

  /**
   * Blood Type Name
   */
  name: string;
}
