/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del Gender a crear.
 */
export interface Gender {
  active?: boolean;
  code: string;
  id?: number;
  name: string;
}
