/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles de la Vaccine a crear.
 */
export interface Vaccine {
  active?: boolean;
  code: string;
  description?: string;
  id?: number;
  name: string;
}
