/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BloodType } from '../models/blood-type';
import { createBloodType } from '../fn/blood-type/create-blood-type';
import { CreateBloodType$Params } from '../fn/blood-type/create-blood-type';
import { deleteBloodType } from '../fn/blood-type/delete-blood-type';
import { DeleteBloodType$Params } from '../fn/blood-type/delete-blood-type';
import { getAllBloodTypes } from '../fn/blood-type/get-all-blood-types';
import { GetAllBloodTypes$Params } from '../fn/blood-type/get-all-blood-types';
import { getBloodTypeById } from '../fn/blood-type/get-blood-type-by-id';
import { GetBloodTypeById$Params } from '../fn/blood-type/get-blood-type-by-id';
import { getPaginatedBloodTypes } from '../fn/blood-type/get-paginated-blood-types';
import { GetPaginatedBloodTypes$Params } from '../fn/blood-type/get-paginated-blood-types';
import { PageResponseDtoBloodType } from '../models/page-response-dto-blood-type';
import { updateBloodType } from '../fn/blood-type/update-blood-type';
import { UpdateBloodType$Params } from '../fn/blood-type/update-blood-type';


/**
 * REST API para gestionar el catálogo maestro de tipos de sangre (MDM).
 */
@Injectable({ providedIn: 'root' })
export class BloodTypeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getBloodTypeById()` */
  static readonly GetBloodTypeByIdPath = '/mdm/blood-type/{id}';

  /**
   * Obtener un Blood Type por ID.
   *
   * Devuelve un objeto Blood Type por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBloodTypeById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBloodTypeById$Response(params: GetBloodTypeById$Params, context?: HttpContext): Observable<StrictHttpResponse<BloodType>> {
    return getBloodTypeById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Blood Type por ID.
   *
   * Devuelve un objeto Blood Type por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBloodTypeById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBloodTypeById(params: GetBloodTypeById$Params, context?: HttpContext): Observable<BloodType> {
    return this.getBloodTypeById$Response(params, context).pipe(
      map((r: StrictHttpResponse<BloodType>): BloodType => r.body)
    );
  }

  /** Path part for operation `updateBloodType()` */
  static readonly UpdateBloodTypePath = '/mdm/blood-type/{id}';

  /**
   * Actualizar un Blood Type por ID.
   *
   * Actualiza un Blood Type existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateBloodType()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBloodType$Response(params: UpdateBloodType$Params, context?: HttpContext): Observable<StrictHttpResponse<BloodType>> {
    return updateBloodType(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Blood Type por ID.
   *
   * Actualiza un Blood Type existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateBloodType$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBloodType(params: UpdateBloodType$Params, context?: HttpContext): Observable<BloodType> {
    return this.updateBloodType$Response(params, context).pipe(
      map((r: StrictHttpResponse<BloodType>): BloodType => r.body)
    );
  }

  /** Path part for operation `deleteBloodType()` */
  static readonly DeleteBloodTypePath = '/mdm/blood-type/{id}';

  /**
   * Blood Type a eliminar por ID.
   *
   * Elimina un Blood Type existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteBloodType()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBloodType$Response(params: DeleteBloodType$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteBloodType(this.http, this.rootUrl, params, context);
  }

  /**
   * Blood Type a eliminar por ID.
   *
   * Elimina un Blood Type existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteBloodType$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBloodType(params: DeleteBloodType$Params, context?: HttpContext): Observable<void> {
    return this.deleteBloodType$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedBloodTypes()` */
  static readonly GetPaginatedBloodTypesPath = '/mdm/blood-type';

  /**
   * Obtiene una lista paginada de Blood Type.
   *
   * Devuelve una lista paginada de Blood Type
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedBloodTypes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedBloodTypes$Response(params?: GetPaginatedBloodTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoBloodType>> {
    return getPaginatedBloodTypes(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Blood Type.
   *
   * Devuelve una lista paginada de Blood Type
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedBloodTypes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedBloodTypes(params?: GetPaginatedBloodTypes$Params, context?: HttpContext): Observable<PageResponseDtoBloodType> {
    return this.getPaginatedBloodTypes$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoBloodType>): PageResponseDtoBloodType => r.body)
    );
  }

  /** Path part for operation `createBloodType()` */
  static readonly CreateBloodTypePath = '/mdm/blood-type';

  /**
   * Crear un Blood Type.
   *
   * Crea un nuevo Blood Type usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createBloodType()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBloodType$Response(params: CreateBloodType$Params, context?: HttpContext): Observable<StrictHttpResponse<BloodType>> {
    return createBloodType(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Blood Type.
   *
   * Crea un nuevo Blood Type usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createBloodType$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBloodType(params: CreateBloodType$Params, context?: HttpContext): Observable<BloodType> {
    return this.createBloodType$Response(params, context).pipe(
      map((r: StrictHttpResponse<BloodType>): BloodType => r.body)
    );
  }

  /** Path part for operation `getAllBloodTypes()` */
  static readonly GetAllBloodTypesPath = '/mdm/blood-type/all';

  /**
   * Obtiene todos los Blood Type.
   *
   * Devuelve la lista completa de Blood Type
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllBloodTypes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBloodTypes$Response(params?: GetAllBloodTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BloodType>>> {
    return getAllBloodTypes(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Blood Type.
   *
   * Devuelve la lista completa de Blood Type
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllBloodTypes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBloodTypes(params?: GetAllBloodTypes$Params, context?: HttpContext): Observable<Array<BloodType>> {
    return this.getAllBloodTypes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<BloodType>>): Array<BloodType> => r.body)
    );
  }

}
