/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CivilStatus } from '../models/civil-status';
import { createCivilStatus } from '../fn/civil-status/create-civil-status';
import { CreateCivilStatus$Params } from '../fn/civil-status/create-civil-status';
import { deleteCivilStatus } from '../fn/civil-status/delete-civil-status';
import { DeleteCivilStatus$Params } from '../fn/civil-status/delete-civil-status';
import { getAllCivilStatuses } from '../fn/civil-status/get-all-civil-statuses';
import { GetAllCivilStatuses$Params } from '../fn/civil-status/get-all-civil-statuses';
import { getCivilStatusById } from '../fn/civil-status/get-civil-status-by-id';
import { GetCivilStatusById$Params } from '../fn/civil-status/get-civil-status-by-id';
import { getPaginatedCivilStatuses } from '../fn/civil-status/get-paginated-civil-statuses';
import { GetPaginatedCivilStatuses$Params } from '../fn/civil-status/get-paginated-civil-statuses';
import { PageResponseDtoCivilStatus } from '../models/page-response-dto-civil-status';
import { updateCivilStatus } from '../fn/civil-status/update-civil-status';
import { UpdateCivilStatus$Params } from '../fn/civil-status/update-civil-status';


/**
 * REST API para gestionar el catálogo de estado civil (MDM).
 */
@Injectable({ providedIn: 'root' })
export class CivilStatusService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCivilStatusById()` */
  static readonly GetCivilStatusByIdPath = '/mdm/demographic/civil-status/{id}';

  /**
   * Obtener un Civil Status por ID.
   *
   * Devuelve un objeto Civil Status por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCivilStatusById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCivilStatusById$Response(params: GetCivilStatusById$Params, context?: HttpContext): Observable<StrictHttpResponse<CivilStatus>> {
    return getCivilStatusById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Civil Status por ID.
   *
   * Devuelve un objeto Civil Status por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCivilStatusById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCivilStatusById(params: GetCivilStatusById$Params, context?: HttpContext): Observable<CivilStatus> {
    return this.getCivilStatusById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CivilStatus>): CivilStatus => r.body)
    );
  }

  /** Path part for operation `updateCivilStatus()` */
  static readonly UpdateCivilStatusPath = '/mdm/demographic/civil-status/{id}';

  /**
   * Actualizar un Civil Status por ID.
   *
   * Actualiza un Civil Status existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCivilStatus()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCivilStatus$Response(params: UpdateCivilStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<CivilStatus>> {
    return updateCivilStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Civil Status por ID.
   *
   * Actualiza un Civil Status existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCivilStatus$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCivilStatus(params: UpdateCivilStatus$Params, context?: HttpContext): Observable<CivilStatus> {
    return this.updateCivilStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<CivilStatus>): CivilStatus => r.body)
    );
  }

  /** Path part for operation `deleteCivilStatus()` */
  static readonly DeleteCivilStatusPath = '/mdm/demographic/civil-status/{id}';

  /**
   * Civil Status a eliminar por ID.
   *
   * Elimina un Civil Status existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCivilStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCivilStatus$Response(params: DeleteCivilStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCivilStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Civil Status a eliminar por ID.
   *
   * Elimina un Civil Status existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCivilStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCivilStatus(params: DeleteCivilStatus$Params, context?: HttpContext): Observable<void> {
    return this.deleteCivilStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedCivilStatuses()` */
  static readonly GetPaginatedCivilStatusesPath = '/mdm/demographic/civil-status';

  /**
   * Obtiene una lista paginada de Civil Status.
   *
   * Devuelve una lista paginada de Civil Status
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedCivilStatuses()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedCivilStatuses$Response(params: GetPaginatedCivilStatuses$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoCivilStatus>> {
    return getPaginatedCivilStatuses(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Civil Status.
   *
   * Devuelve una lista paginada de Civil Status
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedCivilStatuses$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedCivilStatuses(params: GetPaginatedCivilStatuses$Params, context?: HttpContext): Observable<PageResponseDtoCivilStatus> {
    return this.getPaginatedCivilStatuses$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoCivilStatus>): PageResponseDtoCivilStatus => r.body)
    );
  }

  /** Path part for operation `createCivilStatus()` */
  static readonly CreateCivilStatusPath = '/mdm/demographic/civil-status';

  /**
   * Crear un Civil Status.
   *
   * Crea un nuevo Civil Status usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCivilStatus()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCivilStatus$Response(params: CreateCivilStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<CivilStatus>> {
    return createCivilStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Civil Status.
   *
   * Crea un nuevo Civil Status usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCivilStatus$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCivilStatus(params: CreateCivilStatus$Params, context?: HttpContext): Observable<CivilStatus> {
    return this.createCivilStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<CivilStatus>): CivilStatus => r.body)
    );
  }

  /** Path part for operation `getAllCivilStatuses()` */
  static readonly GetAllCivilStatusesPath = '/mdm/demographic/civil-status/all';

  /**
   * Obtiene todos los Civil Status.
   *
   * Devuelve la lista completa de Civil Status
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCivilStatuses()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCivilStatuses$Response(params?: GetAllCivilStatuses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CivilStatus>>> {
    return getAllCivilStatuses(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Civil Status.
   *
   * Devuelve la lista completa de Civil Status
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCivilStatuses$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCivilStatuses(params?: GetAllCivilStatuses$Params, context?: HttpContext): Observable<Array<CivilStatus>> {
    return this.getAllCivilStatuses$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CivilStatus>>): Array<CivilStatus> => r.body)
    );
  }

}
