/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createGender } from '../fn/gender/create-gender';
import { CreateGender$Params } from '../fn/gender/create-gender';
import { deleteGender } from '../fn/gender/delete-gender';
import { DeleteGender$Params } from '../fn/gender/delete-gender';
import { Gender } from '../models/gender';
import { getAllGenders } from '../fn/gender/get-all-genders';
import { GetAllGenders$Params } from '../fn/gender/get-all-genders';
import { getGenderById } from '../fn/gender/get-gender-by-id';
import { GetGenderById$Params } from '../fn/gender/get-gender-by-id';
import { getPaginatedGenders } from '../fn/gender/get-paginated-genders';
import { GetPaginatedGenders$Params } from '../fn/gender/get-paginated-genders';
import { PageResponseDtoGender } from '../models/page-response-dto-gender';
import { updateGender } from '../fn/gender/update-gender';
import { UpdateGender$Params } from '../fn/gender/update-gender';


/**
 * REST API para gestionar el catálogo de géneros (MDM).
 */
@Injectable({ providedIn: 'root' })
export class GenderService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getGenderById()` */
  static readonly GetGenderByIdPath = '/mdm/demographic/gender/{id}';

  /**
   * Obtener un Gender por ID.
   *
   * Devuelve un objeto Gender por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGenderById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGenderById$Response(params: GetGenderById$Params, context?: HttpContext): Observable<StrictHttpResponse<Gender>> {
    return getGenderById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Gender por ID.
   *
   * Devuelve un objeto Gender por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGenderById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGenderById(params: GetGenderById$Params, context?: HttpContext): Observable<Gender> {
    return this.getGenderById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Gender>): Gender => r.body)
    );
  }

  /** Path part for operation `updateGender()` */
  static readonly UpdateGenderPath = '/mdm/demographic/gender/{id}';

  /**
   * Actualizar un Gender por ID.
   *
   * Actualiza un Gender existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateGender()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateGender$Response(params: UpdateGender$Params, context?: HttpContext): Observable<StrictHttpResponse<Gender>> {
    return updateGender(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Gender por ID.
   *
   * Actualiza un Gender existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateGender$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateGender(params: UpdateGender$Params, context?: HttpContext): Observable<Gender> {
    return this.updateGender$Response(params, context).pipe(
      map((r: StrictHttpResponse<Gender>): Gender => r.body)
    );
  }

  /** Path part for operation `deleteGender()` */
  static readonly DeleteGenderPath = '/mdm/demographic/gender/{id}';

  /**
   * Gender a eliminar por ID.
   *
   * Elimina un Gender existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteGender()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteGender$Response(params: DeleteGender$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteGender(this.http, this.rootUrl, params, context);
  }

  /**
   * Gender a eliminar por ID.
   *
   * Elimina un Gender existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteGender$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteGender(params: DeleteGender$Params, context?: HttpContext): Observable<void> {
    return this.deleteGender$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedGenders()` */
  static readonly GetPaginatedGendersPath = '/mdm/demographic/gender';

  /**
   * Obtiene una lista paginada de Gender.
   *
   * Devuelve una lista paginada de Gender
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedGenders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedGenders$Response(params: GetPaginatedGenders$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoGender>> {
    return getPaginatedGenders(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Gender.
   *
   * Devuelve una lista paginada de Gender
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedGenders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedGenders(params: GetPaginatedGenders$Params, context?: HttpContext): Observable<PageResponseDtoGender> {
    return this.getPaginatedGenders$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoGender>): PageResponseDtoGender => r.body)
    );
  }

  /** Path part for operation `createGender()` */
  static readonly CreateGenderPath = '/mdm/demographic/gender';

  /**
   * Crear un Gender.
   *
   * Crea un nuevo Gender usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createGender()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createGender$Response(params: CreateGender$Params, context?: HttpContext): Observable<StrictHttpResponse<Gender>> {
    return createGender(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Gender.
   *
   * Crea un nuevo Gender usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createGender$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createGender(params: CreateGender$Params, context?: HttpContext): Observable<Gender> {
    return this.createGender$Response(params, context).pipe(
      map((r: StrictHttpResponse<Gender>): Gender => r.body)
    );
  }

  /** Path part for operation `getAllGenders()` */
  static readonly GetAllGendersPath = '/mdm/demographic/gender/all';

  /**
   * Obtiene todos los Gender.
   *
   * Devuelve la lista completa de Gender
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllGenders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllGenders$Response(params?: GetAllGenders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Gender>>> {
    return getAllGenders(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Gender.
   *
   * Devuelve la lista completa de Gender
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllGenders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllGenders(params?: GetAllGenders$Params, context?: HttpContext): Observable<Array<Gender>> {
    return this.getAllGenders$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Gender>>): Array<Gender> => r.body)
    );
  }

}
