/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createIdentificationType } from '../fn/identification-type/create-identification-type';
import { CreateIdentificationType$Params } from '../fn/identification-type/create-identification-type';
import { deleteIdentificationType } from '../fn/identification-type/delete-identification-type';
import { DeleteIdentificationType$Params } from '../fn/identification-type/delete-identification-type';
import { getAllIdentificationTypes } from '../fn/identification-type/get-all-identification-types';
import { GetAllIdentificationTypes$Params } from '../fn/identification-type/get-all-identification-types';
import { getIdentificationTypeById } from '../fn/identification-type/get-identification-type-by-id';
import { GetIdentificationTypeById$Params } from '../fn/identification-type/get-identification-type-by-id';
import { getPaginatedIdentificationTypes } from '../fn/identification-type/get-paginated-identification-types';
import { GetPaginatedIdentificationTypes$Params } from '../fn/identification-type/get-paginated-identification-types';
import { IdentificationType } from '../models/identification-type';
import { PageResponseDtoIdentificationType } from '../models/page-response-dto-identification-type';
import { updateIdentificationType } from '../fn/identification-type/update-identification-type';
import { UpdateIdentificationType$Params } from '../fn/identification-type/update-identification-type';


/**
 * REST API para gestionar el catálogo de tipos de identificación (MDM).
 */
@Injectable({ providedIn: 'root' })
export class IdentificationTypeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getIdentificationTypeById()` */
  static readonly GetIdentificationTypeByIdPath = '/mdm/identification-type/{id}';

  /**
   * Obtener un Identification Type por ID.
   *
   * Devuelve un objeto Identification Type por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getIdentificationTypeById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIdentificationTypeById$Response(params: GetIdentificationTypeById$Params, context?: HttpContext): Observable<StrictHttpResponse<IdentificationType>> {
    return getIdentificationTypeById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Identification Type por ID.
   *
   * Devuelve un objeto Identification Type por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getIdentificationTypeById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIdentificationTypeById(params: GetIdentificationTypeById$Params, context?: HttpContext): Observable<IdentificationType> {
    return this.getIdentificationTypeById$Response(params, context).pipe(
      map((r: StrictHttpResponse<IdentificationType>): IdentificationType => r.body)
    );
  }

  /** Path part for operation `updateIdentificationType()` */
  static readonly UpdateIdentificationTypePath = '/mdm/identification-type/{id}';

  /**
   * Actualizar un Identification Type por ID.
   *
   * Actualiza un Identification Type existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateIdentificationType()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateIdentificationType$Response(params: UpdateIdentificationType$Params, context?: HttpContext): Observable<StrictHttpResponse<IdentificationType>> {
    return updateIdentificationType(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Identification Type por ID.
   *
   * Actualiza un Identification Type existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateIdentificationType$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateIdentificationType(params: UpdateIdentificationType$Params, context?: HttpContext): Observable<IdentificationType> {
    return this.updateIdentificationType$Response(params, context).pipe(
      map((r: StrictHttpResponse<IdentificationType>): IdentificationType => r.body)
    );
  }

  /** Path part for operation `deleteIdentificationType()` */
  static readonly DeleteIdentificationTypePath = '/mdm/identification-type/{id}';

  /**
   * Identification Type a eliminar por ID.
   *
   * Elimina un Identification Type existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteIdentificationType()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteIdentificationType$Response(params: DeleteIdentificationType$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteIdentificationType(this.http, this.rootUrl, params, context);
  }

  /**
   * Identification Type a eliminar por ID.
   *
   * Elimina un Identification Type existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteIdentificationType$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteIdentificationType(params: DeleteIdentificationType$Params, context?: HttpContext): Observable<void> {
    return this.deleteIdentificationType$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedIdentificationTypes()` */
  static readonly GetPaginatedIdentificationTypesPath = '/mdm/identification-type';

  /**
   * Obtiene una lista paginada de Identification Type.
   *
   * Devuelve una lista paginada de Identification Type
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedIdentificationTypes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedIdentificationTypes$Response(params: GetPaginatedIdentificationTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoIdentificationType>> {
    return getPaginatedIdentificationTypes(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Identification Type.
   *
   * Devuelve una lista paginada de Identification Type
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedIdentificationTypes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedIdentificationTypes(params: GetPaginatedIdentificationTypes$Params, context?: HttpContext): Observable<PageResponseDtoIdentificationType> {
    return this.getPaginatedIdentificationTypes$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoIdentificationType>): PageResponseDtoIdentificationType => r.body)
    );
  }

  /** Path part for operation `createIdentificationType()` */
  static readonly CreateIdentificationTypePath = '/mdm/identification-type';

  /**
   * Crear un Identification Type.
   *
   * Crea un nuevo Identification Type usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createIdentificationType()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createIdentificationType$Response(params: CreateIdentificationType$Params, context?: HttpContext): Observable<StrictHttpResponse<IdentificationType>> {
    return createIdentificationType(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Identification Type.
   *
   * Crea un nuevo Identification Type usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createIdentificationType$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createIdentificationType(params: CreateIdentificationType$Params, context?: HttpContext): Observable<IdentificationType> {
    return this.createIdentificationType$Response(params, context).pipe(
      map((r: StrictHttpResponse<IdentificationType>): IdentificationType => r.body)
    );
  }

  /** Path part for operation `getAllIdentificationTypes()` */
  static readonly GetAllIdentificationTypesPath = '/mdm/identification-type/all';

  /**
   * Obtiene todos los Identification Type.
   *
   * Devuelve la lista completa de Identification Type
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllIdentificationTypes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllIdentificationTypes$Response(params?: GetAllIdentificationTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IdentificationType>>> {
    return getAllIdentificationTypes(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Identification Type.
   *
   * Devuelve la lista completa de Identification Type
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllIdentificationTypes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllIdentificationTypes(params?: GetAllIdentificationTypes$Params, context?: HttpContext): Observable<Array<IdentificationType>> {
    return this.getAllIdentificationTypes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<IdentificationType>>): Array<IdentificationType> => r.body)
    );
  }

}
