/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createKinship } from '../fn/kinship/create-kinship';
import { CreateKinship$Params } from '../fn/kinship/create-kinship';
import { deleteKinship } from '../fn/kinship/delete-kinship';
import { DeleteKinship$Params } from '../fn/kinship/delete-kinship';
import { getAllKinships } from '../fn/kinship/get-all-kinships';
import { GetAllKinships$Params } from '../fn/kinship/get-all-kinships';
import { getKinshipById } from '../fn/kinship/get-kinship-by-id';
import { GetKinshipById$Params } from '../fn/kinship/get-kinship-by-id';
import { getPaginatedKinships } from '../fn/kinship/get-paginated-kinships';
import { GetPaginatedKinships$Params } from '../fn/kinship/get-paginated-kinships';
import { Kinship } from '../models/kinship';
import { PageResponseDtoKinship } from '../models/page-response-dto-kinship';
import { updateKinship } from '../fn/kinship/update-kinship';
import { UpdateKinship$Params } from '../fn/kinship/update-kinship';


/**
 * REST API para gestionar el catálogo maestro de parentescos (MDM).
 */
@Injectable({ providedIn: 'root' })
export class KinshipService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getKinshipById()` */
  static readonly GetKinshipByIdPath = '/mdm/kinship/{id}';

  /**
   * Obtener un Kinship por ID.
   *
   * Devuelve un objeto Kinship por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getKinshipById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getKinshipById$Response(params: GetKinshipById$Params, context?: HttpContext): Observable<StrictHttpResponse<Kinship>> {
    return getKinshipById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Kinship por ID.
   *
   * Devuelve un objeto Kinship por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getKinshipById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getKinshipById(params: GetKinshipById$Params, context?: HttpContext): Observable<Kinship> {
    return this.getKinshipById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Kinship>): Kinship => r.body)
    );
  }

  /** Path part for operation `updateKinship()` */
  static readonly UpdateKinshipPath = '/mdm/kinship/{id}';

  /**
   * Actualizar un Kinship por ID.
   *
   * Actualiza un Kinship existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateKinship()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateKinship$Response(params: UpdateKinship$Params, context?: HttpContext): Observable<StrictHttpResponse<Kinship>> {
    return updateKinship(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Kinship por ID.
   *
   * Actualiza un Kinship existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateKinship$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateKinship(params: UpdateKinship$Params, context?: HttpContext): Observable<Kinship> {
    return this.updateKinship$Response(params, context).pipe(
      map((r: StrictHttpResponse<Kinship>): Kinship => r.body)
    );
  }

  /** Path part for operation `deleteKinship()` */
  static readonly DeleteKinshipPath = '/mdm/kinship/{id}';

  /**
   * Kinship a eliminar por ID.
   *
   * Elimina un Kinship existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteKinship()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteKinship$Response(params: DeleteKinship$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteKinship(this.http, this.rootUrl, params, context);
  }

  /**
   * Kinship a eliminar por ID.
   *
   * Elimina un Kinship existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteKinship$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteKinship(params: DeleteKinship$Params, context?: HttpContext): Observable<void> {
    return this.deleteKinship$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedKinships()` */
  static readonly GetPaginatedKinshipsPath = '/mdm/kinship';

  /**
   * Obtiene una lista paginada de Kinship.
   *
   * Devuelve una lista paginada de Kinship
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedKinships()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedKinships$Response(params: GetPaginatedKinships$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoKinship>> {
    return getPaginatedKinships(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Kinship.
   *
   * Devuelve una lista paginada de Kinship
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedKinships$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedKinships(params: GetPaginatedKinships$Params, context?: HttpContext): Observable<PageResponseDtoKinship> {
    return this.getPaginatedKinships$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoKinship>): PageResponseDtoKinship => r.body)
    );
  }

  /** Path part for operation `createKinship()` */
  static readonly CreateKinshipPath = '/mdm/kinship';

  /**
   * Crear un Kinship.
   *
   * Crea un nuevo Kinship usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createKinship()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createKinship$Response(params: CreateKinship$Params, context?: HttpContext): Observable<StrictHttpResponse<Kinship>> {
    return createKinship(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Kinship.
   *
   * Crea un nuevo Kinship usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createKinship$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createKinship(params: CreateKinship$Params, context?: HttpContext): Observable<Kinship> {
    return this.createKinship$Response(params, context).pipe(
      map((r: StrictHttpResponse<Kinship>): Kinship => r.body)
    );
  }

  /** Path part for operation `getAllKinships()` */
  static readonly GetAllKinshipsPath = '/mdm/kinship/all';

  /**
   * Obtiene todos los Kinship.
   *
   * Devuelve la lista completa de Kinship
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllKinships()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllKinships$Response(params?: GetAllKinships$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Kinship>>> {
    return getAllKinships(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Kinship.
   *
   * Devuelve la lista completa de Kinship
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllKinships$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllKinships(params?: GetAllKinships$Params, context?: HttpContext): Observable<Array<Kinship>> {
    return this.getAllKinships$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Kinship>>): Array<Kinship> => r.body)
    );
  }

}
