/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTheme } from '../fn/theme/create-theme';
import { CreateTheme$Params } from '../fn/theme/create-theme';
import { deleteTheme } from '../fn/theme/delete-theme';
import { DeleteTheme$Params } from '../fn/theme/delete-theme';
import { getAllThemes } from '../fn/theme/get-all-themes';
import { GetAllThemes$Params } from '../fn/theme/get-all-themes';
import { getPaginatedThemes } from '../fn/theme/get-paginated-themes';
import { GetPaginatedThemes$Params } from '../fn/theme/get-paginated-themes';
import { getThemeById } from '../fn/theme/get-theme-by-id';
import { GetThemeById$Params } from '../fn/theme/get-theme-by-id';
import { getThemeByTenant } from '../fn/theme/get-theme-by-tenant';
import { GetThemeByTenant$Params } from '../fn/theme/get-theme-by-tenant';
import { PageResponseDtoThemeDto } from '../models/page-response-dto-theme-dto';
import { ThemeDto } from '../models/theme-dto';
import { updateTheme } from '../fn/theme/update-theme';
import { UpdateTheme$Params } from '../fn/theme/update-theme';
import { upgradeTheme } from '../fn/theme/upgrade-theme';
import { UpgradeTheme$Params } from '../fn/theme/upgrade-theme';
import { uploadLogo } from '../fn/theme/upload-logo';
import { UploadLogo$Params } from '../fn/theme/upload-logo';


/**
 * REST API para gestionar detalles de temas visuales: crear, actualizar, obtener y eliminar.
 */
@Injectable({ providedIn: 'root' })
export class ThemeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getThemeById()` */
  static readonly GetThemeByIdPath = '/themes/{id}';

  /**
   * Obtener un Theme por ID.
   *
   * Devuelve un objeto Theme por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getThemeById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getThemeById$Response(params: GetThemeById$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return getThemeById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Theme por ID.
   *
   * Devuelve un objeto Theme por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getThemeById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getThemeById(params: GetThemeById$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.getThemeById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

  /** Path part for operation `updateTheme()` */
  static readonly UpdateThemePath = '/themes/{id}';

  /**
   * Actualizar un Theme por ID.
   *
   * Actualiza un Theme existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTheme()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTheme$Response(params: UpdateTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return updateTheme(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Theme por ID.
   *
   * Actualiza un Theme existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTheme$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTheme(params: UpdateTheme$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.updateTheme$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

  /** Path part for operation `deleteTheme()` */
  static readonly DeleteThemePath = '/themes/{id}';

  /**
   * Theme a eliminar por ID.
   *
   * Elimina un Theme existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTheme()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTheme$Response(params: DeleteTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteTheme(this.http, this.rootUrl, params, context);
  }

  /**
   * Theme a eliminar por ID.
   *
   * Elimina un Theme existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTheme$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTheme(params: DeleteTheme$Params, context?: HttpContext): Observable<void> {
    return this.deleteTheme$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getThemeByTenant()` */
  static readonly GetThemeByTenantPath = '/themes/tenant/{tenantCode}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getThemeByTenant()` instead.
   *
   * This method doesn't expect any request body.
   */
  getThemeByTenant$Response(params: GetThemeByTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return getThemeByTenant(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getThemeByTenant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getThemeByTenant(params: GetThemeByTenant$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.getThemeByTenant$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

  /** Path part for operation `upgradeTheme()` */
  static readonly UpgradeThemePath = '/themes/tenant/{tenantCode}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `upgradeTheme()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  upgradeTheme$Response(params: UpgradeTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return upgradeTheme(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `upgradeTheme$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  upgradeTheme(params: UpgradeTheme$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.upgradeTheme$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

  /** Path part for operation `getPaginatedThemes()` */
  static readonly GetPaginatedThemesPath = '/themes';

  /**
   * Obtiene una lista paginada de Theme.
   *
   * Devuelve una lista paginada de Theme
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedThemes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedThemes$Response(params?: GetPaginatedThemes$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoThemeDto>> {
    return getPaginatedThemes(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Theme.
   *
   * Devuelve una lista paginada de Theme
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedThemes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedThemes(params?: GetPaginatedThemes$Params, context?: HttpContext): Observable<PageResponseDtoThemeDto> {
    return this.getPaginatedThemes$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoThemeDto>): PageResponseDtoThemeDto => r.body)
    );
  }

  /** Path part for operation `createTheme()` */
  static readonly CreateThemePath = '/themes';

  /**
   * Crear un Theme.
   *
   * Crea un nuevo Theme usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTheme()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTheme$Response(params: CreateTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return createTheme(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Theme.
   *
   * Crea un nuevo Theme usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTheme$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTheme(params: CreateTheme$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.createTheme$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

  /** Path part for operation `uploadLogo()` */
  static readonly UploadLogoPath = '/themes/tenant/{tenantCode}/logo';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadLogo()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadLogo$Response(params: UploadLogo$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return uploadLogo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadLogo$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadLogo(params: UploadLogo$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.uploadLogo$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

  /** Path part for operation `getAllThemes()` */
  static readonly GetAllThemesPath = '/themes/all';

  /**
   * Obtiene todos los Theme.
   *
   * Devuelve la lista completa de Theme
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllThemes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllThemes$Response(params?: GetAllThemes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ThemeDto>>> {
    return getAllThemes(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Theme.
   *
   * Devuelve la lista completa de Theme
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllThemes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllThemes(params?: GetAllThemes$Params, context?: HttpContext): Observable<Array<ThemeDto>> {
    return this.getAllThemes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ThemeDto>>): Array<ThemeDto> => r.body)
    );
  }

}
