/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseDtoVaccine } from '../../models/page-response-dto-vaccine';
import { VaccineSearchDto } from '../../models/vaccine-search-dto';

export interface GetPaginatedVaccines$Params {
  searchDto: VaccineSearchDto;

/**
 * Índice de la página a recuperar.
 */
  pageIndex: number;

/**
 * Tamaño de la página.
 */
  pageSize: number;
}

export function getPaginatedVaccines(http: HttpClient, rootUrl: string, params: GetPaginatedVaccines$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoVaccine>> {
  const rb = new RequestBuilder(rootUrl, getPaginatedVaccines.PATH, 'get');
  if (params) {
    rb.query('searchDto', params.searchDto, {});
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoVaccine>;
    })
  );
}

getPaginatedVaccines.PATH = '/mdm/vaccine';
