/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Vaccine } from '../../models/vaccine';

export interface UpdateVaccine$Params {

/**
 * ID de la Vaccine a actualizar.
 */
  id: number;
      body: Vaccine
}

export function updateVaccine(http: HttpClient, rootUrl: string, params: UpdateVaccine$Params, context?: HttpContext): Observable<StrictHttpResponse<Vaccine>> {
  const rb = new RequestBuilder(rootUrl, updateVaccine.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Vaccine>;
    })
  );
}

updateVaccine.PATH = '/mdm/vaccine/{id}';
