-- ============================================
-- Script: V0_1__create_theme.sql
-- Tabla: THEME
-- ============================================
CREATE TABLE IF NOT EXISTS THEME (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    
    -- Branding
    LOGO_URL VARCHAR(1000),
    FAVICON_URL VARCHAR(1000),
    
    -- Colors (Angular Material Palette)
    PRIMARY_COLOR VARCHAR(20),
    SECONDARY_COLOR VARCHAR(20),
    BACKGROUND_COLOR VARCHAR(20),
    TEXT_COLOR VARCHAR(20),
    ACCENT_COLOR VARCHAR(20),
    WARN_COLOR VARCHAR(20),
    LINK_COLOR VARCHAR(20),
    BUTTON_TEXT_COLOR VARCHAR(20),
    
    -- Typography & Extra
    FONT_FAMILY VARCHAR(100),
    THEME_MODE VARCHAR(10), -- ENUM 'LIGHT', 'DARK', 'AUTO'
    PROPERTIES_JSON TEXT,
    CUSTOM_CSS TEXT,
    
    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
