CREATE TABLE IF NOT EXISTS AUT_BLACKLISTED_TOKEN (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TOKEN VARCHAR(500) NOT NULL,
    BLACKLISTED_AT DATETIME NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    CONSTRAINT UK_BLACKLISTEDTOKEN_TOKEN UNIQUE (TOKEN)
);