
CREATE TABLE IF NOT EXISTS AUT_AUDIT_EVENTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TENANT_ID VARCHAR(50) NOT NULL,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0 NOT NULL,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    USER_ID BIGINT NOT NULL,
    MESSAGE VARCHAR(500) NOT NULL,
    TIMESTAMP DATETIME(6) NOT NULL,
    IP_ADDRESS VARCHAR(255) NULL,

    -- Índices recomendados para auditoría
    INDEX IDX_AUDIT_EVENTS_USER (USER_ID),
    INDEX IDX_AUDIT_EVENTS_TENANT (TENANT_ID),
    INDEX IDX_AUDIT_EVENTS_TYPE (EVENT_TYPE),
    INDEX IDX_AUDIT_EVENTS_TIMESTAMP (TIMESTAMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

