CREATE TABLE IF NOT EXISTS AUT_PASSWORD_RESET_TOKEN (
   ID BIGINT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
   TOKEN VARCHAR(255) NOT NULL,
   EXPIRATION_DATE DATETIME NOT NULL,
   USER_ID BIGINT NOT NULL,
   USED BIT(1) DEFAULT 0 NOT NULL,
   CONSTRAINT UK_PASSWORDRESETTOKEN_TOKEN UNIQUE (TOKEN),
   CONSTRAINT FK_RESET_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES AUT_USER (ID)
);
