-- Script: V4_1__create_aut_user.sql
-- Módulo: core-auth
-- Descripción: Creación de la tabla AUT_USER con metadatos y auditoría.
CREATE TABLE IF NOT EXISTS AUT_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(50) NOT NULL,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0 NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ACCOUNT_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_LOGIN DATETIME(6) NULL DEFAULT NULL,
    PERSON_ID BIGINT,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME(6) NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),

    -- Constraints
    CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_USER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES DMN_PERSON(ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
