
CREATE TABLE IF NOT EXISTS AUT_AUDIT_LOG (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EVENT_TYPE ENUM('USER_LOGIN','USER_LOGOUT', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'TOKEN_REFRESH') NOT NULL,
    USER_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,
    MESSAGE VARCHAR(500) NOT NULL,
    TIMESTAMP DATETIME(6) NOT NULL,
    IP_ADDRESS VARCHAR(255) NULL,

    -- Índices recomendados para auditoría
    INDEX IDX_AUDIT_EVENTS_USER (USER_ID),
    INDEX IDX_AUDIT_EVENTS_TENANT (TENANT_ID),
    INDEX IDX_AUDIT_EVENTS_TYPE (EVENT_TYPE),
    INDEX IDX_AUDIT_EVENTS_TIMESTAMP (TIMESTAMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

