-- Script: V4_1__create_aut_user.sql
-- Módulo: core-auth
-- Descripción: Creación de la tabla AUT_USER con metadatos y auditoría.
CREATE TABLE IF NOT EXISTS AUT_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ACCOUNT_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_LOGIN TIMESTAMP NULL DEFAULT NULL,
    PERSON_ID BIGINT,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE AUT_USER
ADD CONSTRAINT FK_USER_PERSON
FOREIGN KEY (PERSON_ID) REFERENCES DMN_PERSON(ID);
