CREATE TABLE IF NOT EXISTS AUT_ROLE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TENANT_ID VARCHAR(50) NOT NULL,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0 NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
