 -- ***********************************************
 --  Insert AUT_ROLE
 -- ***********************************************
INSERT INTO AUT_ROLE (ID, TENANT_ID, NAME, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES
    (1, 'SYSTEM', "ROLE_SUPER_ADMIN", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (2, 'SYSTEM', "ROLE_ADMIN", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (3, 'SYSTEM', "ROLE_DOCTOR", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (4, 'SYSTEM', "ROLE_NURSE", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (5, 'SYSTEM', "ROLE_PATIENT", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (6, 'SYSTEM', "ROLE_EMPLOYEE", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (7, 'SYSTEM', "ROLE_USER", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (8, 'SYSTEM', "ROLE_GUEST", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (9, 'SYSTEM', "ROLE_MODERATOR", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (10, 'SYSTEM', "ROLE_CONTENT_CREATOR", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (11, 'SYSTEM', "ROLE_CONTENT_EDITOR", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (12, 'SYSTEM', "ROLE_SUPPORT", "SYSTEM", CURRENT_TIMESTAMP, null, null),
    (13, 'SYSTEM', "ROLE_ANALYST", "SYSTEM", CURRENT_TIMESTAMP, null, null);

commit;
