CREATE TABLE IF NOT EXISTS AUT_ROLE_PERMISSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CONSTRAINT UK_ROLE_PERMISSION UNIQUE (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_ROLE_PERMISSION_ROLE FOREIGN KEY (ROLE_ID) REFERENCES AUT_ROLE (ID),
    CONSTRAINT FK_ROLE_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES AUT_PERMISSION (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
