
CREATE TABLE IF NOT EXISTS AUT_USER_ACCOUNT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TENANT_ID VARCHAR(50) NOT NULL,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0 NOT NULL,
    USER_ID BIGINT NOT NULL,
    PERSON_ID BIGINT NOT NULL,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME(6) NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),

    -- Constraints
    CONSTRAINT FK_USER_ACCOUNTUSER FOREIGN KEY (USER_ID) REFERENCES AUT_USER(ID),
    CONSTRAINT FK_USER_ACCOUNTTENANT FOREIGN KEY (TENANT_ID) REFERENCES DMN_TENANT(CODE)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
