
CREATE TABLE IF NOT EXISTS AUT_USER_ACCOUNT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    PERSON_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    -- Constraints
    CONSTRAINT FK_USER_ACCOUNTUSER FOREIGN KEY (USER_ID) REFERENCES AUT_USER(ID),
    CONSTRAINT FK_USER_ACCOUNTTENANT FOREIGN KEY (TENANT_ID) REFERENCES DMN_TENANT(ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;