
CREATE TABLE IF NOT EXISTS AUT_ACTIVATION_TOKEN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    TOKEN VARCHAR(100) NOT NULL UNIQUE,

    USER_ID BIGINT NOT NULL,
    TENANT_ID BIGINT NOT NULL,

    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED BOOLEAN NOT NULL DEFAULT FALSE,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    -- Constraints
    CONSTRAINT FK_ACTIVATION_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES AUT_USER(ID),
    CONSTRAINT FK_ACTIVATION_TOKEN_TENANT FOREIGN KEY (TENANT_ID) REFERENCES DMN_TENANT(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Índices opcionales
CREATE INDEX IDX_ACTIVATION_TOKEN_USER ON AUT_ACTIVATION_TOKEN(USER_ID);
CREATE INDEX IDX_ACTIVATION_TOKEN_TENANT ON AUT_ACTIVATION_TOKEN(TENANT_ID);
CREATE INDEX IDX_ACTIVATION_TOKEN_TOKEN ON AUT_ACTIVATION_TOKEN(TOKEN);