
CREATE TABLE IF NOT EXISTS AUT_USER_TENANT_ROLE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TENANT_ID VARCHAR(50) NOT NULL,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0 NOT NULL,
    FK_ID_USER BIGINT NOT NULL,
    FK_ID_ROLE BIGINT NOT NULL,
    ASSIGNED_AT DATETIME(6) NOT NULL,
    REVOKED_AT DATETIME(6) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    
    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME(6) NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),

    -- Constraints
    CONSTRAINT UK_USER_TENANT_ROLE UNIQUE (FK_ID_USER, TENANT_ID, FK_ID_ROLE),

    -- Foreign Keys
    CONSTRAINT FK_USERTENANTROLE_USER
        FOREIGN KEY (FK_ID_USER) REFERENCES AUT_USER (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_USERTENANTROLE_TENANT
        FOREIGN KEY (TENANT_ID) REFERENCES DMN_TENANT (CODE)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_USERTENANTROLE_ROLE
        FOREIGN KEY (FK_ID_ROLE) REFERENCES AUT_ROLE (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Índices para mejorar el rendimiento de las consultas
CREATE INDEX IDX_USERTENANTROLE_USER ON AUT_USER_TENANT_ROLE (FK_ID_USER);
CREATE INDEX IDX_USERTENANTROLE_TENANT ON AUT_USER_TENANT_ROLE (TENANT_ID);
CREATE INDEX IDX_USERTENANTROLE_ROLE ON AUT_USER_TENANT_ROLE (FK_ID_ROLE);
CREATE INDEX IDX_USERTENANTROLE_ACTIVE ON AUT_USER_TENANT_ROLE (ACTIVE);
CREATE INDEX IDX_USERTENANTROLE_ASSIGNED_AT ON AUT_USER_TENANT_ROLE (ASSIGNED_AT);
CREATE INDEX IDX_USERTENANTROLE_REVOKED_AT ON AUT_USER_TENANT_ROLE (REVOKED_AT);
