
CREATE TABLE IF NOT EXISTS AUT_USER_TENANT_ROLE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_USER BIGINT NOT NULL,
    FK_ID_TENANT BIGINT NOT NULL,
    FK_ID_ROLE BIGINT NOT NULL,
    ASSIGNED_AT DATETIME NOT NULL,
    REVOKED_AT DATETIME NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    
    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_USER_TENANT_ROLE UNIQUE (FK_ID_USER, FK_ID_TENANT, FK_ID_ROLE),

    -- Foreign Keys
    CONSTRAINT FK_USERTENANTROLE_USER
        FOREIGN KEY (FK_ID_USER) REFERENCES AUT_USER (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_USERTENANTROLE_TENANT
        FOREIGN KEY (FK_ID_TENANT) REFERENCES DMN_TENANT (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_USERTENANTROLE_ROLE
        FOREIGN KEY (FK_ID_ROLE) REFERENCES AUT_ROLE (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Índices para mejorar el rendimiento de las consultas
CREATE INDEX IDX_USERTENANTROLE_USER ON AUT_USER_TENANT_ROLE (FK_ID_USER);
CREATE INDEX IDX_USERTENANTROLE_TENANT ON AUT_USER_TENANT_ROLE (FK_ID_TENANT);
CREATE INDEX IDX_USERTENANTROLE_ROLE ON AUT_USER_TENANT_ROLE (FK_ID_ROLE);
CREATE INDEX IDX_USERTENANTROLE_ACTIVE ON AUT_USER_TENANT_ROLE (ACTIVE);
CREATE INDEX IDX_USERTENANTROLE_ASSIGNED_AT ON AUT_USER_TENANT_ROLE (ASSIGNED_AT);
CREATE INDEX IDX_USERTENANTROLE_REVOKED_AT ON AUT_USER_TENANT_ROLE (REVOKED_AT);