-- *******************************************************
-- Script de creación de tabla MGT_EMPLOYEE
-- *******************************************************

CREATE TABLE IF NOT EXISTS MGT_EMPLOYEE (
    ID BIGINT PRIMARY KEY,
--    EMPLOYEE_TYPE VARCHAR(40) NOT NULL,
    EMPLOYEE_TYPE ENUM('ADMINISTRATIVO','MEDICO','ENFERMERO','TECNICO','LABORATORISTA', 'FARMACEUTICO', 'OTRO') NOT NULL,
--    EMPLOYEE_STATUS VARCHAR(30) NOT NULL,
    EMPLOYEE_STATUS ENUM('ACTIVO','INACTIVO','SUSPENDIDO','LICENCIA','BAJA') NOT NULL,
    PROFESION VARCHAR(150),
    PUESTO VARCHAR(120),
    CARGO VARCHAR(120),
    NRO_COLEGIO_MEDICO VARCHAR(50),
    FECHA_INGRESO DATE,
    FECHA_SALIDA DATE,
    FK_ID_USER BIGINT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
