-- *******************************************************
-- Script de creación de tabla MGT_TENANT_ADMIN
-- *******************************************************

CREATE TABLE IF NOT EXISTS MGT_TENANT_ADMIN (
    ID BIGINT PRIMARY KEY NOT NULL,
    ADMIN_LEVEL ENUM('LEVEL_1','LEVEL_2','LEVEL_3') NOT NULL,
    TENANT_CODE VARCHAR(100) NOT NULL,
    USER_ID BIGINT NOT NULL,

    CONSTRAINT FK_TENANT_ADMIN_PERSON FOREIGN KEY (ID) REFERENCES DMN_PERSON(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TENANT_ADMIN_TENANT FOREIGN KEY (TENANT_CODE) REFERENCES DMN_TENANT(CODE)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_TENANT_ADMIN_USER FOREIGN KEY (USER_ID) REFERENCES AUT_USER(ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT UK_TENANT_ADMIN_USER UNIQUE (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_TENANT_ADMIN_TENANT ON MGT_TENANT_ADMIN (TENANT_CODE);