-- ============================================
-- Tabla: MUNICIPIO
-- Descripción: Creación de la tabla MUNICIPIO con restricciones
-- ============================================

CREATE TABLE IF NOT EXISTS MUNICIPIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(200),
    CODIGO_MUNICIPIO INT,
    POBLACION INT,
    SUPERFICIE DECIMAL(15,2),

    FK_ID_PROVINCIA BIGINT NOT NULL,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(100) NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_NOMBRE_MUNICIPIO UNIQUE (NOMBRE),
    CONSTRAINT FK_MUNICIPIO_PROVINCIA FOREIGN KEY (FK_ID_PROVINCIA) 
        REFERENCES PROVINCIA (ID)
        ON DELETE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
