-- ============================================
-- Tabla: GEO_MUNICIPALITY
-- Descripción: Creación de la tabla GEO_MUNICIPALITY con restricciones
-- ============================================
CREATE TABLE IF NOT EXISTS GEO_MUNICIPALITY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(200),
    MUNICIPALITY_CODE INT,
    POPULATION INT,
    SURFACE DECIMAL(15,2),

    FK_ID_PROVINCE BIGINT NOT NULL,

    -- Concurrencia e ID Externo (Tier Elite)
    VERSION BIGINT NOT NULL DEFAULT 0,
    EXTERNAL_ID VARCHAR(36) NOT NULL UNIQUE,

    -- Auditoría
    CREATED_BY          VARCHAR(100) NOT NULL,
    CREATED_DATE        DATETIME(6)  NOT NULL,
    LAST_MODIFIED_BY    VARCHAR(100),
    LAST_MODIFIED_DATE  DATETIME(6),

    -- Constraints
    CONSTRAINT UK_MUNICIPALITY_NAME_PROVINCE UNIQUE (NAME, FK_ID_PROVINCE),
    CONSTRAINT FK_MUNICIPALITY_PROVINCE FOREIGN KEY (FK_ID_PROVINCE)
        REFERENCES GEO_PROVINCE (ID)
        ON DELETE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
