-- ============================================
-- Tabla: GEO_MUNICIPIO
-- Descripción: Creación de la tabla GEO_MUNICIPIO con restricciones
-- ============================================

CREATE TABLE IF NOT EXISTS GEO_MUNICIPIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(200),
    CODIGO_MUNICIPIO INT,
    POBLACION INT,
    SUPERFICIE DECIMAL(15,2),

    FK_ID_PROVINCIA BIGINT NOT NULL,

    -- Concurrencia e ID Externo (Tier Elite)
    VERSION BIGINT NOT NULL DEFAULT 0,
    EXTERNAL_ID VARCHAR(36)  NOT NULL UNIQUE,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_NOMBRE_MUNICIPIO_PROVINCIA UNIQUE (NOMBRE, FK_ID_PROVINCIA),
    CONSTRAINT FK_MUNICIPIO_PROVINCIA FOREIGN KEY (FK_ID_PROVINCIA)
        REFERENCES GEO_PROVINCIA (ID)
        ON DELETE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
