/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BloodType } from '../../models/blood-type';

export interface UpdateBloodType$Params {

/**
 * ID del Blood Type a actualizar.
 */
  id: number;
      body: BloodType
}

export function updateBloodType(http: HttpClient, rootUrl: string, params: UpdateBloodType$Params, context?: HttpContext): Observable<StrictHttpResponse<BloodType>> {
  const rb = new RequestBuilder(rootUrl, updateBloodType.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BloodType>;
    })
  );
}

updateBloodType.PATH = '/mdm/blood-type/{id}';
