-- ============================================
-- Script: V3_2__create_dmn_tenant.sql
-- Tabla: DMN_TENANT
-- ============================================

CREATE TABLE IF NOT EXISTS DMN_TENANT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(20) NOT NULL, --('HOSPITAL','CLINIC','LABORATORY','PHARMACY', 'GLOBAL'),
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    DESCRIPTION TEXT,
    
    -- MGT_THEME Relation (Mapped directly here)
    THEME_ID BIGINT NULL,
    ADDRESS_ID BIGINT NULL,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_TENANT_CODE  UNIQUE (CODE),
    CONSTRAINT FK_TENANT_THEME FOREIGN KEY (THEME_ID) REFERENCES DMN_THEME(ID)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Índices adicionales
CREATE INDEX IDX_TENANT_NAME ON DMN_TENANT(NAME);
COMMIT;
