-- *******************************************************
-- Script de creación de tabla DMN_PERSON_TENANT
-- *******************************************************

CREATE TABLE IF NOT EXISTS DMN_PERSON_TENANT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_PERSON BIGINT NOT NULL,
    FK_ID_TENANT BIGINT NOT NULL,
    NATIONAL_HEALTH_ID VARCHAR(50),
    ROLE_CONTEXT ENUM ('SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'PATIENT', 'NURSE', 'EMPLOYEE', 'RECEPTIONIST', 'LAB_TECHNICIAN', 'PHARMACIST', 'ACCOUNTANT', 'AUDITOR', 'PARAMEDIC', 'SOCIAL_WORKER', 'THERAPIST', 'PSYCHOLOGIST', 'NUTRITIONIST', 'GUEST') NOT NULL,

    DATE_REGISTERED TIMESTAMP NOT NULL,
    DATE_UNREGISTERED TIMESTAMP,
    RELATION_STATUS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', 'TERMINATED', 'EXPIRED', 'ARCHIVED', 'LOCKED', 'DEACTIVATED') NOT NULL,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE TIMESTAMP,

    -- Constraints
    CONSTRAINT UK_PERSON_TENANT_ROLE_CONTEXT UNIQUE (FK_ID_PERSON, FK_ID_TENANT, ROLE_CONTEXT),
    CONSTRAINT FK_PERSON_TENANT_PERSON FOREIGN KEY (FK_ID_PERSON) REFERENCES DMN_PERSON(ID),
    CONSTRAINT FK_PERSON_TENANT_TENANT FOREIGN KEY (FK_ID_TENANT) REFERENCES DMN_TENANT(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
